### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by AcediaJin** [cyruzzo/AboveVTT#1026]
**Error:**
```
Failed to start AboveVTT on https://www.dndbeyond.com/characters/96025953?abovevtt=true
TypeError: Failed to fetch
Error: TypeError: Failed to fetch
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:98:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:39:9
```
**Environment:**
```
{"avttVersion":"0.88","browser":{"name":"Chrome","version":"111","mozilla":false,"chrome":true,"msie":false,"opera":false}}
```

**Comment by AcediaJin** [comment]
has anyone a Idea what to do?

**Comment by AcediaJin** [comment]
yeah I joined from the character page - cuz if I join from the campain page I only get to the home page of DnD-Beyond

**Comment by AcediaJin** [comment]
oh, if I try to edit the char in the campain window - it just reloads the page...

**Comment by Azmoria** [comment]
> oh, if I try to edit the char in the campain window - it just reloads the page...

I think this was mentioned on discord 2-3 weeks ago too. I dunno if they found a resolution but they found some info here
https://discord.com/channels/815028457851191326/852495991227809802/1081741040899346523

**Comment by AcediaJin** [comment]
thank I will check it out. 

funny enough I can edit a unassigned char but not my own...

**Comment by Josh-Archer** [comment]
I was able to reproduce this issue. It might be if you have a second character sheet open (from another campaign). Once I closed the tab with that sheet, it loaded immediately.

**Comment by Josh-Archer** [comment]
I reproduced this by accident. If you opena sheet not related to the campaign loaded in AboveVTT, then it triggers. I fixed by closing out the other sheets/campaign pages. Sometimes I just get a black screen though. Guessing it is related to how the playerTokenId is pulled?

**Comment by Azmoria** [comment]
Cleaning up old issues that are stale. I haven't seen any `ERR_CERT_AUTHORITY_INVALID` errors so I assume this was resolved at the time. If it does reoccur please open a new issue.
