### ISSUE TITLE
Import fails while setting `soundpads` 

### ISSUE THREAD

**Issue by vlaminck** [cyruzzo/AboveVTT#1072]
This is where the failure happens `Settings.js:969:23`
```
		for(let k in DataFile.soundpads){
			window.SOUNDPADS[k]=DataFile.soundpads[k];
		}
```

**Error:**
```
exception undefined
Uncaught TypeError: Cannot set properties of undefined (setting 'DEMO')
chrome-extension://npnilipfnlgdkcmbejdmebllefkaphdg/Settings.js:969:23
TypeError: Cannot set properties of undefined (setting 'DEMO')
    at reader.onload (chrome-extension://npnilipfnlgdkcmbejdmebllefkaphdg/Settings.js:969:23)
Error: exception undefined
    at addLog (chrome-extension://npnilipfnlgdkcmbejdmebllefkaphdg/CoreFunctions.js:90:21)
    at chrome-extension://npnilipfnlgdkcmbejdmebllefkaphdg/CoreFunctions.js:100:7
    at r (https://media.dndbeyond.com/encounter-builder/static/js/main.0a407125.js:2:1302258)
```
**Environment:**
```
{"avttVersion":"0.90-local","browser":{"name":"Chrome","version":"111","mozilla":false,"chrome":true,"msie":false,"opera":false}}
```
**Other Logs:**
```

EXCEPTION 2023-03-29T14:31:16.599Z
      Uncaught TypeError: Cannot set properties of undefined (setting 'DEMO')
      chrome-extension://npnilipfnlgdkcmbejdmebllefkaphdg/Settings.js:969:23
      TypeError: Cannot set properties of undefined (setting 'DEMO')
    at reader.onload (chrome-extension://npnilipfnlgdkcmbejdmebllefkaphdg/Settings.js:969:23)

LOG 2023-03-29T14:31:16.597Z
      showErrorMessage
      Uncaught TypeError: Cannot set properties of undefined (setting 'DEMO')
      chrome-extension://npnilipfnlgdkcmbejdmebllefkaphdg/Settings.js:969:23
      {}

EXCEPTION 2023-03-29T14:31:16.594Z
      Uncaught TypeError: Cannot set properties of undefined (setting 'DEMO')
      chrome-extension://npnilipfnlgdkcmbejdmebllefkaphdg/Settings.js:969:23

LOG 2023-03-29T14:31:13.142Z
      disable_peer_manager

LOG 2023-03-29T14:31:13.142Z
      stop_sending_cursor_to_peers

LOG 2023-03-29T14:31:13.141Z
      configure_peer_manager_from_settings

LOG 2023-03-29T14:31:13.112Z
      remove_sidebar_flyout

LOG 2023-03-29T14:31:10.807Z
      [audio]
      user interaction detected, starting mixer

LOG 2023-03-29T14:31:10.490Z
      search_monster pagination 
      2698
      0
   
```

**Comment by Azmoria** [comment]
I'm guessing we also have to add the new audio to export then
