### ISSUE TITLE
set_window_name_and_image has failed after 30 attempts

### ISSUE THREAD

**Issue by davaguco** [cyruzzo/AboveVTT#1074]
**Error:**
```
set_window_name_and_image has failed after 30 attempts

Error: set_window_name_and_image has failed after 30 attempts
    at set_window_name_and_image (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CharactersPage.js:199:17)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CharactersPage.js:219:7
```
**Environment:**
```
{"avttVersion":"0.89","browser":{"name":"Chrome","version":"111","mozilla":false,"chrome":true,"msie":false,"opera":false}}
```
**Other Logs:**
```

WARN 2023-03-29T17:40:03.613Z
      set_window_name_and_image has failed after 30 attempts

LOG 2023-03-29T17:40:02.771Z
      lock_gamelog_open couldn't find the sidebar. Trying again in 1 second

LOG 2023-03-29T17:40:01.771Z
      lock_gamelog_open couldn't find the sidebar. Trying again in 1 second

LOG 2023-03-29T17:40:00.764Z
      lock_gamelog_open couldn't find the sidebar. Trying again in 1 second

LOG 2023-03-29T17:39:59.754Z
      lock_gamelog_open couldn't find the sidebar. Trying again in 1 second

LOG 2023-03-29T17:39:58.745Z
      lock_gamelog_open couldn't find the sidebar. Trying again in 1 second

LOG 2023-03-29T17:39:57.739Z
      lock_gamelog_open couldn't find the sidebar. Trying again in 1 second

LOG 2023-03-29T17:39:56.727Z
      lock_gamelog_open couldn't find the sidebar. Trying again in 1 second

LOG 2023-03-29T17:39:55.723Z
      lock_gamelog_open couldn't find the sidebar. Trying again in 1 second

LOG 2023-03-29T17:39:54.720Z
      lock_gamelog_open couldn't find the sidebar. Trying again in 1 second

LOG 2023-03-29T17:39:53.716Z
      lock_gamelog_open couldn't find the sidebar. Trying again in 1 second

LOG 2023-03-29T17:39:52.712Z
      lock_gamelog_open couldn't find the sidebar. Trying again in 1 second

LOG 2023-03-29T17:39:51.706Z
      lock_gamelog_open couldn't find the sidebar. Trying again in 1 second

LOG 2023-03-29T17:39:50.704Z
      lock_gamelog_open couldn't find the sidebar. Trying again in 1 second

LOG 2023-03-29T17:39:49.700Z
```

**Comment by davaguco** [comment]
No, I hadnt placer one ability on my character, it wasnt complete, so it
produced this error. I finished my character creation and now works fine.
