### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'getItem')

### ISSUE THREAD

**Issue by lkarnes81** [cyruzzo/AboveVTT#1100]
**Error:**
```
Failed to start AboveVTT on https://www.dndbeyond.com/characters/97700676?abovevtt=true
TypeError: Cannot read properties of null (reading 'getItem')
Error: TypeError: Cannot read properties of null (reading 'getItem')
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:98:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:39:9
```
**Environment:**
```
{"avttVersion":"0.88","browser":{"name":"Chrome","version":"110","mozilla":false,"chrome":true,"msie":false,"opera":false}}
```

**Comment by Azmoria** [comment]
Cleaning up older issues - I believe this was resolved or no longer occurs. If it is occurring please open a new issue so we can get info matching the current version.
