### ISSUE TITLE
promiseRejection undefined

### ISSUE THREAD

**Issue by vlaminck** [cyruzzo/AboveVTT#1178]
This error doesn't seem to cause any problems, but I noticed it while debugging something else. Here's the log in the console

<img width="648" alt="Screenshot 2023-04-29 at 8 12 26 AM" src="https://user-images.githubusercontent.com/584771/235304687-657a1fb7-5251-4ff1-9e6a-15dff643cb6f.png">

If I set a breakpoint on the line where it breaks, I see that `selectedPlaylistID` is set to a UUID, but it doesn't match the key in `state.playlists` so this line breaks
```
state.playlists[selectedPlaylistID].channels = state.channels;
```

I also captured these logs using the `Alert Every Concerning Log` feature just in case it gave any extra insight

**Error:**
```
promiseRejection undefined

undefined: undefined:undefined

Error: promiseRejection undefined
    at addLog (chrome-extension://npnilipfnlgdkcmbejdmebllefkaphdg/CoreFunctions.js:92:21)
    at window.onunhandledrejection (chrome-extension://npnilipfnlgdkcmbejdmebllefkaphdg/CoreFunctions.js:126:7)
```
**Environment:**
```
{"avttVersion":"0.94-local","browser":{"name":"Chrome","version":"112","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

PROMISEREJECTION 2023-04-29T13:06:35.012Z
      undefined
      undefined: undefined:undefined
      undefined

LOG 2023-04-29T13:06:35.010Z
      {"action":"sendmessage","campaignId":"[REDACTED]","eventType":"custom/myVTT/mixer","sender":"51ab8d37-1991-4351-b4e1-66d0422fff95","data":{"paused":false,"channels":{},"playlists":{"4e715926-4572-4e46-aea6-7617a6cbf169":{"channels":{},"volume":0.5,"paused":false,"name":"Default"}},"selected":"4e715926-4572-4e46-aea6-7617a6cbf169"},"cloud":1,"sequence":29,"sceneId":"498d11a9-71b1-48f3-83f8-bd581c974952","playersSceneId":"498d11a9-71b1-48f3-83f8-bd581c974952","requestTimeEpoch":"1682773594904"}

LOG 2023-04-29T13:06:35.010Z
      custom/myVTT/mixer

LOG 2023-04-29T13:06:35.010Z
      [audio]
      remote mixer update received
      {"paused":false,"playlists":{"4e715926-4572-4e46-aea6-7617a6cbf169":{"channels":{},"volume":0.5,"paused":false,"name":"Default"}},"selected":"4e715926-4572-4e46-aea6-7617a6cbf169"}

LOG 2023-04-29T13:06:34.657Z
      do_check_token_visibility

LOG 2023-04-29T13:06:34.636Z
      Diff: 9

LOG 2023-04-29T13:06:34.635Z
      Setting combat tracker opacity to 1.0

LOG 2023-04-29T13:06:34.634Z
      cerco ida95d0912-c4f5-41e9-8d1c-6ad4c987a746

LOG 2023-04-29T13:06:34.633Z
      LOADING TOKENS!

LOG 2023-04-29T13:06:34.619Z
      restoring zoom level
      {"title":"Stone","zoom":0.625,"leftOffset":804,"topOffset":1177}

LOG 2023-04-29T13:06:34.619Z
      zoom
      0.625
      undefined
      undefined


```

**Comment by Azmoria** [comment]
This error should be fixed in #1176 if you're seeing it player side. It's DM only data that sets playlist info. Players don't need to set that info as the DM sends them the new state after changing playlists.

If you're seeing it DM side I'm not sure what would be causing that.

The animated map volume slider is always visible yeh, we could probably display:none or visibility:hidden it if it really feels off. I think it being visible is fine though especially for a new user settings appear/disappearing might make them miss it.

**Comment by Azmoria** [comment]
Clean up old issues - seems it may have been resolved from above.
