### ISSUE TITLE
DDB API Error: EncounterNotFoundException Encounter does not exist

### ISSUE THREAD

**Issue by larryleveen** [cyruzzo/AboveVTT#1197]
**Error:**
```
DDB API Error: EncounterNotFoundException Encounter does not exist
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/6eba3dd2-e53a-4c71-99e5-686dee810de8?abovevtt=true
Error: DDB API Error: EncounterNotFoundException Encounter does not exist
    at lookForErrors (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:36:11)
    at async DDBApi.fetchJsonWithCredentials (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:55:21)
    at async DDBApi.fetchEncounter (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:105:22)
    at async harvest_game_id (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:619:27)
```
**Environment:**
```
{"avttVersion":"0.94","browser":{"name":"Chrome","version":"113","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

ERROR 2023-05-13T02:10:35.198Z
      DDB API Error: EncounterNotFoundException Encounter does not exist

LOG 2023-05-13T02:10:35.086Z
      startup_step Gathering basic campaign info

LOG 2023-05-13T02:10:35.083Z
      startup calling init_splash
```

**Comment by Azmoria** [comment]
This could be a broken encounter or you may not have a free encounter slot. Could also have just been a blip on dndbeyonds servers. 

We load the DM view overtop of an encounter so if you have a free account make sure you have at least 1 available. 
If it's not that if you've been joining via a bookmark or the error happened on refresh try using the join as DM button to launch.

If those don't get it working let us know.
