### ISSUE TITLE
ReferenceError: ga is not defined

### ISSUE THREAD

**Issue by Charlez27** [cyruzzo/AboveVTT#1203]
**Error:**
```
ReferenceError: ga is not defined
Failed to start AboveVTT on https://www.dndbeyond.com/characters/99897090?abovevtt=true
Error: ReferenceError: ga is not defined
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:288:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:43:9
```
**Environment:**
```
{"avttVersion":"0.94","browser":{"name":"Chrome","version":"113","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-05-17T02:25:22.445Z
      set_avtt_setting_value aggressiveErrorMessages is now false

LOG 2023-05-17T02:25:21.158Z
      startup_step Gathering basic campaign info

LOG 2023-05-17T02:25:21.158Z
      DDBApi is refreshing auth token

LOG 2023-05-17T02:25:21.148Z
      startup calling init_splash

WARN 2023-05-17T02:25:21.130Z
      DiceRoller failed to get ddbMB
```

**Comment by Chrysostomus** [comment]
I got the same issue when trying to join campaign. Tested with
- 2 browsers, Firefox and Vivaldi (cache cleared)
- Two campaigns, old and newly created
- As DM and as player. 
- 2 OS, Windows and Linux

With or without extension, I get 403 from Dndbeyond encounterbuilder. Therefore I suspect that this is an issue with dndbeyond, not abovevtt.

**Comment by Azmoria** [comment]
A hotfix should be available in the extensions stores now

**Comment by Azmoria** [comment]
Looks like this was mostly due to a dndbeyond server issue
