### ISSUE TITLE
ReferenceError: ga is not defined

### ISSUE THREAD

**Issue by roseoh631** [cyruzzo/AboveVTT#1206]
**Error:**
```
ReferenceError: ga is not defined
Failed to start AboveVTT on https://www.dndbeyond.com/characters/99827334?abovevtt=true
Error: ReferenceError: ga is not defined
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:288:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:43:9
```
**Environment:**
```
{"avttVersion":"0.94","browser":{"name":"Chrome","version":"113","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-05-17T08:13:01.184Z
      set_avtt_setting_value aggressiveErrorMessages is now false

LOG 2023-05-17T08:12:59.806Z
      DDBApi is refreshing auth token

LOG 2023-05-17T08:12:59.805Z
      startup_step Gathering basic campaign info

LOG 2023-05-17T08:12:59.804Z
      startup calling init_splash

WARN 2023-05-17T08:12:59.771Z
      DiceRoller failed to get ddbMB
```

**Comment by Azmoria** [comment]
A hotfix should be available in the extensions stores now

**Comment by Azmoria** [comment]
Looks like this was mostly due to a dndbeyond server issue
