### ISSUE TITLE
ReferenceError: ga is not defined

### ISSUE THREAD

**Issue by sernaton** [cyruzzo/AboveVTT#1210]
**Error:**
```
ReferenceError: ga is not defined
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/3dd5f705-6834-457c-be40-35b689471cc2?abovevtt=true
Error: ReferenceError: ga is not defined
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:288:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:43:9
```
**Environment:**
```
{"avttVersion":"0.94","browser":{"name":"Chrome","version":"113","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-05-17T12:02:32.532Z
      set_avtt_setting_value aggressiveErrorMessages is now [REDACTED]

LOG 2023-05-17T12:02:32.376Z
      startup_step Gathering basic campaign info

LOG 2023-05-17T12:02:32.375Z
      startup calling init_splash

WARN 2023-05-17T12:02:32.364Z
      DiceRoller failed to get ddbMB
```

**Comment by Azmoria** [comment]
A hotfix should be available in the extensions stores now

**Comment by sernaton** [comment]
that's great, but it seems dndbeyond is down (showing 403s everywhere), so that's the main issue - hopefully they will fix it soon.

**Comment by Azmoria** [comment]
ah yeh - we got a report of another error for another user too so it may be related to that.

**Comment by Azmoria** [comment]
Looks like this was mostly due to a dndbeyond server issue
