### ISSUE TITLE
DDB API Error: Unknown Error 404 

### ISSUE THREAD

**Issue by ryantake** [cyruzzo/AboveVTT#1212]
**Error:**
```
DDB API Error: Unknown Error 404 
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/3c6e9e06-d221-4f06-99c5-0eca04bbce67?abovevtt=true
Error: DDB API Error: Unknown Error 404 
    at lookForErrors (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:36:11)
    at async DDBApi.fetchJsonWithToken (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:49:21)
    at async DDBApi.fetchCharacterDetails (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:206:22)
    at async DDBApi.fetchCampaignCharacterDetails (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:192:12)
    at async rebuild_window_pcs (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:505:30)
    at async start_above_vtt_common (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:89:3)
    at async start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:116:3)
```
**Environment:**
```
{"avttVersion":"0.94.1-local","browser":{"name":"Chrome","version":"112","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

ERROR 2023-05-17T17:55:10.913Z
      DDB API Error: Unknown Error 404 

LOG 2023-05-17T17:55:10.266Z
      startup_step Gathering player character data

LOG 2023-05-17T17:55:09.893Z
      startup_step Starting AboveVTT for DM

LOG 2023-05-17T17:55:09.893Z
      start_above_vtt_common

LOG 2023-05-17T17:55:09.893Z
      DDBApi.fetchCampaignInfo

LOG 2023-05-17T17:55:09.893Z
      DDBApi is refreshing auth token

LOG 2023-05-17T17:55:09.892Z
      harvest_campaign_secret found it in localStorage

LOG 2023-05-17T17:55:09.684Z
      startup_step Gathering basic campaign info

LOG 2023-05-17T17:55:09.682Z
      startup calling init_splash
```

**Comment by ryantake** [comment]
Hello! I've been using your awesome VTT for some years now and really appreciate all the work the team has put into it! In that past few months, I stopped being able to access one of my campaigns. I can open others, this one just seems to be the problem child. Thanks for looking into it!

**Comment by Azmoria** [comment]
I know dndbeyond was having some issues yesterday - this may have been after they were resolved though. This looks like the dndbeyond API isn't giving us some information, I'm hoping it was just server issues on their end.

 If not check characters names don't have special characters in them just in case that might be causing issue.

**Comment by ryantake** [comment]
Alas, just tried again and getting a similar error. The PC name seems normal enough to me. :(

**Comment by Azmoria** [comment]
I'm cleaning up some older issues - I'm closing this just due to it being stale. Feel free to open a new issue if it's still occuring.

I wasn't able to track down the exact cause but it may be related to recent issue of DDB's 'are you human' check preventing requests - there's been an uptick in reports of this across DDBs forums and discord (not just abovevtt related).

For some reason you may have to check an incognito window to see and clear the are you a bot message. Closing just due to duplicate for now - still on our radar to see if it's something we can resolve or a DDB issue.
