### ISSUE TITLE
DDB API Error: EncounterNotFoundException Encounter does not exist

### ISSUE THREAD

**Issue by gindavis** [cyruzzo/AboveVTT#1229]
**Error:**
```
DDB API Error: EncounterNotFoundException Encounter does not exist
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/b8449658-1ffb-4b2f-9be5-3d1903c27abf?abovevtt=true
Error: DDB API Error: EncounterNotFoundException Encounter does not exist
    at lookForErrors (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:36:11)
    at async DDBApi.fetchJsonWithCredentials (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:55:21)
    at async DDBApi.fetchEncounter (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:105:22)
    at async harvest_game_id (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:619:27)
```
**Environment:**
```
{"avttVersion":"0.95","browser":{"name":"Chrome","version":"113","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

ERROR 2023-05-29T16:43:47.691Z
      DDB API Error: EncounterNotFoundException Encounter does not exist

LOG 2023-05-29T16:43:47.632Z
      startup_step Gathering basic campaign info

LOG 2023-05-29T16:43:47.617Z
      startup calling init_splash
```

**Comment by gindavis** [comment]
I did a refresh and got this...

**Comment by Azmoria** [comment]
This generally happens when an encounter breaks on dndbeyond. If you back out and rejoin using the `join as DM` button it should generally work. If it doesn't let us know.
