### ISSUE TITLE
Can not create new custom tokens

### ISSUE THREAD

**Issue by natemoonlife** [cyruzzo/AboveVTT#1244]
**Error:**
```

Failed to create My Token
{"id":"c0c10eb0-6899-4951-b90d-62c3a5cf2cab","parentId":"myTokensFolder","rootId":"myTokensFolder","tokenOptions":{"name":"New Token 4"},"tokenType":"myToken"}
Error
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:288:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/TokensPanel.js:1315:13
    at persist_token_customization (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/TokenCustomization.js:640:9)
    at create_token_inside (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/TokensPanel.js:1308:5)
    at HTMLButtonElement.<anonymous> (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/SidebarPanel.js:1131:11)
    at HTMLButtonElement.dispatch (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/jquery-3.6.0.min.js:2:43064)
    at v.handle (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/jquery-3.6.0.min.js:2:41048)
    at HTMLButtonElement.r (https://media.dndbeyond.com/encounter-builder/static/js/main.ba302dd1.js:2:1301967)</anonymous>
```
**Environment:**
```
{"avttVersion":"0.95","browser":{"name":"Chrome","version":"114","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-06-13T06:43:44.566Z
      build_sidebar_list_row
      zombie door no heads

LOG 2023-06-13T06:43:44.566Z
      set_list_item_identifier
      /My Tokens/TOA/zombie door no heads
      e394eb80-2013-4752-bee1-d9f63a04fbe1

LOG 2023-06-13T06:43:44.564Z
      build_sidebar_list_row
      zombie door

LOG 2023-06-13T06:43:44.564Z
      set_list_item_identifier
      /My Tokens/TOA/zombie door
      16fd15c1-1a9e-4bc3-90d4-0f4b0775a54f

LOG 2023-06-13T06:43:44.562Z
      build_sidebar_list_row
      Zelona

LOG 2023-06-13T06:43:44.562Z
      set_list_item_identifier
      /My Tokens/NPC'S/Zelona
      f291f4fb-16c4-454d-a20c-df4a526eac55

LOG 2023-06-13T06:43:44.561Z
      folder.collapsed: true
      {"id":"4ef7f23e-c25d-427b-aa3e-e53f38
```

**Comment by Azmoria** [comment]
This was due to local storage being full - a campaign nate deleted didn't delete the associated notes. If we can detect that and remove notes from local storage that would be good.

**Comment by Azmoria** [comment]
I believe we resolved this.
