### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by AvGoose001** [cyruzzo/AboveVTT#1245]
**Error:**
```
TypeError: Failed to fetch
Failed to start AboveVTT on https://www.dndbeyond.com/characters/100734930?abovevtt=true
Error: TypeError: Failed to fetch
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:288:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:43:9
```
**Environment:**
```
{"avttVersion":"0.95","browser":{"name":"Chrome","version":"114","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-06-13T19:11:03.806Z
      startup_step Gathering player character data

LOG 2023-06-13T19:11:03.246Z
      DDBApi is refreshing auth token

LOG 2023-06-13T19:11:03.245Z
      start_above_vtt_common

LOG 2023-06-13T19:11:03.245Z
      DDBApi.fetchCampaignInfo

LOG 2023-06-13T19:11:03.244Z
      harvest_campaign_secret found it in localStorage

LOG 2023-06-13T19:11:03.244Z
      startup_step Starting AboveVTT for character

LOG 2023-06-13T19:11:03.218Z
      set_avtt_setting_value aggressiveErrorMessages is now false

LOG 2023-06-13T19:11:03.163Z
      startup_step Gathering basic campaign info

LOG 2023-06-13T19:11:03.161Z
      startup calling init_splash
```

**Comment by AvGoose001** [comment]
On launching

**Comment by Azmoria** [comment]
Our server is currently down due to issues on AWS's end. They have info on their service health page about it now so hopefully they will be able to resolve it soon.

**Comment by Azmoria** [comment]
this was an aws issue and should be resolved
