### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by Fellow2003** [cyruzzo/AboveVTT#1246]
**Error:**
```
TypeError: Failed to fetch
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/5fa0871b-3986-4320-a4f2-9ec27699166a?abovevtt=true
Error: TypeError: Failed to fetch
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:288:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:43:9
```
**Environment:**
```
{"avttVersion":"0.95","browser":{"name":"Chrome","version":"114","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-06-13T19:05:36.103Z
      startup_step Gathering player character data

LOG 2023-06-13T19:05:35.684Z
      DDBApi.fetchCampaignInfo

LOG 2023-06-13T19:05:35.684Z
      DDBApi is refreshing auth token

LOG 2023-06-13T19:05:35.683Z
      startup_step Starting AboveVTT for DM

LOG 2023-06-13T19:05:35.683Z
      start_above_vtt_common

LOG 2023-06-13T19:05:35.682Z
      harvest_campaign_secret found it in localStorage

LOG 2023-06-13T19:05:35.676Z
      set_avtt_setting_value aggressiveErrorMessages is now false

LOG 2023-06-13T19:05:35.604Z
      startup_step Gathering basic campaign info

LOG 2023-06-13T19:05:35.595Z
      startup calling init_splash
```

**Comment by Azmoria** [comment]
Our server is currently down due to issues on AWS's end. They have info on their service health page about it now so hopefully they will be able to resolve it soon.

**Comment by Azmoria** [comment]
this was an aws issue and should be resolved
