### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by Tynethor1** [cyruzzo/AboveVTT#1248]
**Error:**
```
TypeError: Failed to fetch
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/54646bd7-cc67-4710-b98f-0b4e851dedd3?abovevtt=true
Error: TypeError: Failed to fetch
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:288:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:43:9
```
**Environment:**
```
{"avttVersion":"0.95","browser":{"name":"Chrome","version":"114","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-06-13T19:14:47.862Z
      startup_step Gathering player character data

LOG 2023-06-13T19:14:47.692Z
      startup_step Starting AboveVTT for DM

LOG 2023-06-13T19:14:47.692Z
      start_above_vtt_common

LOG 2023-06-13T19:14:47.692Z
      DDBApi.fetchCampaignInfo

LOG 2023-06-13T19:14:47.692Z
      DDBApi is refreshing auth token

LOG 2023-06-13T19:14:47.691Z
      harvest_campaign_secret found it in localStorage

LOG 2023-06-13T19:14:47.688Z
      set_avtt_setting_value aggressiveErrorMessages is now false

LOG 2023-06-13T19:14:47.630Z
      startup_step Gathering basic campaign info

LOG 2023-06-13T19:14:47.628Z
      startup calling init_splash
```

**Comment by Azmoria** [comment]
this was an aws issue and should be resolved
