### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by Mariannaruru** [cyruzzo/AboveVTT#1250]
**Error:**
```
TypeError: Failed to fetch
Failed to start AboveVTT on https://www.dndbeyond.com/characters/85522253?abovevtt=true
Error: TypeError: Failed to fetch
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:288:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:43:9
```
**Environment:**
```
{"avttVersion":"0.95","browser":{"name":"Chrome","version":"114","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

ERROR 2023-06-13T19:30:04.846Z
      Failed to get messages
      {}

LOG 2023-06-13T19:30:04.520Z
      Babylon.js v6.3.0 - WebGL2 - Parallel shader compilation

LOG 2023-06-13T19:30:04.126Z
      startup_step Gathering player character data

LOG 2023-06-13T19:30:03.937Z
      FFM CONTAINER
      {"release-gate-ims":false,"release-gate.tactical-maps":false,"release-gate-gfs-blessings-ui":false,"release-gate-character-sheet-campaign-settings":false,"release-gate-character-sheet-tour":false,"release-gate-random-name-multiple-suggestions":true,"release-gate-premade-characters":null}

LOG 2023-06-13T19:30:03.765Z
      start_above_vtt_common

LOG 2023-06-13T19:30:03.765Z
      DDBApi.fetchCampaignInfo

LOG 2023-06-13T19:30:03.764Z
      harvest_campaign_secret found it in localStorage

LOG 2023-06-13T19:30:03.764Z
      startup_step Starting AboveVTT for character

LOG 2023-06-13T19:30:03.761Z
      set_avtt_setting_value aggressiveErrorMessages is now false

LOG 2023-06-13T19:30:03.181Z
      startup_step Gathering basic campaign info

LOG 2023-06-13T19:30:03.181Z
      DDBApi is refreshing auth token

LOG 2023-06-13T19:30:03.178Z
      startup calling init_splash
```

**Comment by Azmoria** [comment]
this was an aws issue and should be resolved
