### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by ETBuzz** [cyruzzo/AboveVTT#1252]
**Error:**
```
TypeError: Failed to fetch
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/8926c92f-795c-48be-af5f-1424e11fde2d?abovevtt=true
Error: TypeError: Failed to fetch
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:288:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:43:9
```
**Environment:**
```
{"avttVersion":"0.95","browser":{"name":"Chrome","version":"114","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-06-13T19:57:35.503Z
      startup_step Gathering player character data

LOG 2023-06-13T19:57:35.233Z
      start_above_vtt_common

LOG 2023-06-13T19:57:35.233Z
      DDBApi.fetchCampaignInfo

LOG 2023-06-13T19:57:35.233Z
      DDBApi is refreshing auth token

LOG 2023-06-13T19:57:35.232Z
      harvest_campaign_secret found it in localStorage

LOG 2023-06-13T19:57:35.232Z
      startup_step Starting AboveVTT for DM

LOG 2023-06-13T19:57:35.231Z
      set_avtt_setting_value aggressiveErrorMessages is now false

LOG 2023-06-13T19:57:35.169Z
      startup_step Gathering basic campaign info

LOG 2023-06-13T19:57:35.167Z
      startup calling init_splash
```

**Comment by Azmoria** [comment]
this was an aws issue and should be resolved
