### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by jakebaez** [cyruzzo/AboveVTT#1253]
**Error:**
```
TypeError: Failed to fetch
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/9c7ed044-3ef7-4543-b5d8-7eb78b422815?abovevtt=true
Error: TypeError: Failed to fetch
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:288:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:43:9
```
**Environment:**
```
{"avttVersion":"0.95","browser":{"name":"Chrome","version":"114","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-06-13T20:10:18.172Z
      startup_step Gathering player character data

LOG 2023-06-13T20:10:17.164Z
      DDBApi.fetchCampaignInfo

LOG 2023-06-13T20:10:17.164Z
      DDBApi is refreshing auth token

LOG 2023-06-13T20:10:17.162Z
      harvest_campaign_secret found it in localStorage

LOG 2023-06-13T20:10:17.162Z
      startup_step Starting AboveVTT for DM

LOG 2023-06-13T20:10:17.162Z
      start_above_vtt_common

LOG 2023-06-13T20:10:17.159Z
      set_avtt_setting_value aggressiveErrorMessages is now false

LOG 2023-06-13T20:10:17.030Z
      startup_step Gathering basic campaign info

LOG 2023-06-13T20:10:17.027Z
      startup calling init_splash
```

**Comment by Azmoria** [comment]
this was an aws issue and should be resolved
