### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by Zslythe** [cyruzzo/AboveVTT#1254]
**Error:**
```
TypeError: Failed to fetch
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/58015297-658f-4a8f-8d3e-46134207070e?abovevtt=true
Error: TypeError: Failed to fetch
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:288:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:43:9
```
**Environment:**
```
{"avttVersion":"0.95","browser":{"name":"Chrome","version":"114","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-06-13T20:18:10.956Z
      startup_step Gathering player character data

LOG 2023-06-13T20:18:10.778Z
      DDBApi.fetchCampaignInfo

LOG 2023-06-13T20:18:10.778Z
      DDBApi is refreshing auth token

LOG 2023-06-13T20:18:10.777Z
      harvest_campaign_secret found it in localStorage

LOG 2023-06-13T20:18:10.777Z
      startup_step Starting AboveVTT for DM

LOG 2023-06-13T20:18:10.777Z
      start_above_vtt_common

LOG 2023-06-13T20:18:10.773Z
      set_avtt_setting_value aggressiveErrorMessages is now false

LOG 2023-06-13T20:18:10.731Z
      startup_step Gathering basic campaign info

LOG 2023-06-13T20:18:10.729Z
      startup calling init_splash
```

**Comment by Azmoria** [comment]
this was an aws issue and should be resolved
