### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by fin255** [cyruzzo/AboveVTT#1255]
**Error:**
```
TypeError: Failed to fetch
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/a3f80c75-18b9-4057-8eba-4ff6301a8642?abovevtt=true
Error: TypeError: Failed to fetch
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:288:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:43:9
```
**Environment:**
```
{"avttVersion":"0.95","browser":{"name":"Chrome","version":"114","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-06-13T20:25:45.564Z
      startup_step Gathering player character data

ERROR 2023-06-13T20:25:45.419Z
      Failed to get messages
      {}

LOG 2023-06-13T20:25:44.990Z
      harvest_campaign_secret found it in localStorage

LOG 2023-06-13T20:25:44.990Z
      startup_step Starting AboveVTT for DM

LOG 2023-06-13T20:25:44.990Z
      start_above_vtt_common

LOG 2023-06-13T20:25:44.990Z
      DDBApi.fetchCampaignInfo

LOG 2023-06-13T20:25:44.990Z
      DDBApi is refreshing auth token

LOG 2023-06-13T20:25:44.988Z
      set_avtt_setting_value aggressiveErrorMessages is now false

LOG 2023-06-13T20:25:44.837Z
      Babylon.js v6.3.0 - WebGL2 - Parallel shader compilation

LOG 2023-06-13T20:25:44.710Z
      startup_step Gathering basic campaign info

LOG 2023-06-13T20:25:44.709Z
      startup calling init_splash
```

**Comment by Azmoria** [comment]
this was an aws issue and should be resolved
