### ISSUE TITLE
Unable to render a DDB chapter. This url does not appear to be a valid DDB chapter https://www.dndbeyond.com/compendium/adventures/wdh/winter-wizardry

### ISSUE THREAD

**Issue by rcamble3** [cyruzzo/AboveVTT#1258]
**Error:**
```
Unable to render a DDB chapter. This url does not appear to be a valid DDB chapter https://www.dndbeyond.com/compendium/adventures/wdh/winter-wizardry

Error: Unable to render a DDB chapter. This url does not appear to be a valid DDB chapter https://www.dndbeyond.com/compendium/adventures/wdh/winter-wizardry
    at render_source_chapter_in_iframe (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Journal.js:1234:13)
    at HTMLDivElement.<anonymous> (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Journal.js:352:7)
    at HTMLDivElement.dispatch (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/jquery-3.6.0.min.js:2:43064)
    at v.handle (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/jquery-3.6.0.min.js:2:41048)
    at HTMLDivElement.r (https://media.dndbeyond.com/encounter-builder/static/js/main.ba302dd1.js:2:1301967)</anonymous>
```
**Environment:**
```
{"avttVersion":"0.95","browser":{"name":"Chrome","version":"114","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

ERROR 2023-06-17T16:25:45.544Z
      render_source_chapter_in_iframe was given an invalid url
      https://www.dndbeyond.com/compendium/adventures/wdh/winter-wizardry

LOG 2023-06-17T16:25:41.485Z
      render_source_chapter_in_iframe is loading https://www.dndbeyond.com/compendium/adventures/wdh/spring-madness
      {"0":{},"length":1}
      {}

LOG 2023-06-17T16:25:33.845Z
      render_source_chapter_in_iframe is loading https://www.dndbeyond.com/compendium/adventures/wdh/spring-madness
      {"0":{},"length":1}
      {}

LOG 2023-06-17T16:25:31.469Z
      find_or_create_generic_draggable_window id: sourceChapterIframe_resizeDrag, titleBarText: Source Book, addLoadingIndicator: true, addPopoutButton: false

LOG 2023-06-17T16:25:31.445Z
      showErrorMessage
      {}

ERROR 2023-06-17T16:25:31.444Z
      render_source_chapter_in_iframe was given an invalid url
      https://www.dndbeyond.com/compendium/adventures/wdh/spr
```

**Comment by Azmoria** [comment]
I'm unable to reproduce this on my end for this chapter. Was this a one off or is this still happening for you? I assume you also have access to this content?

**Comment by rcamble3** [comment]
It is happening to me consistently. The odd thing is that the content loads just fine, it just tells me the link is invalid. Sent from my iPhoneOn Jun 18, 2023, at 4:23 AM, Azmoria ***@***.***> wrote:﻿
I'm unable to reproduce this on my end for this chapter. Was this a one off or is this still happening for you? I assume you also have access to this content?

**Comment by Azmoria** [comment]
I think I found the issue - we are looking at the URL and looking for /sources after dndbeyond.com but some books use compendium in the url I guess now?

Either way it should be resolved next release. Thanks for the report.

**Comment by rcamble3** [comment]
Awesome, thanks for the update!
