### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Ron-A-R** [cyruzzo/AboveVTT#1263]
**Error:**
```
Internal Server Error
Failed to start AboveVTT on https://www.dndbeyond.com/characters/76178684?abovevtt=true
Error: Internal Server Error
    at AboveApi.checkForErrors (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/AboveApi.js:52:13)
    at AboveApi.fetchJson (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/AboveApi.js:46:10)
    at async AboveApi.getScene (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/AboveApi.js:102:22)
    at async start_above_vtt_for_players (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:193:25)
```
**Environment:**
```
{"avttVersion":"0.95","browser":{"name":"Chrome","version":"114","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-06-19T02:21:29.317Z
      AboveApi.getCurrentScene
      {"dmscene":"cb590355-934c-4af1-b790-21a8749facf6","playerscene":"8ecc8c15-be20-4f8c-bc56-7a5da12fc9f4"}

LOG 2023-06-19T02:21:29.119Z
      Received 
      {"id":"e1fe0896-b47d-4a88-b215-b9870656e818","dateTime":"1680123342124","gameId":"3714453","userId":"100184270","source":"web","data":{"action":"custom","rolls":[{"diceNotation":{"set":[{"count":2,"dieType":"d20","dice":[{"dieType":"d20","dieValue":16},{"dieType":"d20","dieValue":15}],"operation":0}],"constant":0},"diceNotationStr":"2d20","rollType":"roll","rollKind":"","result":{"constant":0,"values":[16,15],"total":31,"text":"16+15"}}],"context":{"entityId":"100184270","entityType":"user","messageScope":"userId","messageTarget":"100184270"},"setId":"03601","rollId":"489539f9-a784-4fea-9d16-fc1926f371f4"},"entityId":"100184270","entityType":"user","eventType":"dice/roll/fulfilled","persist":true,"messageScope":"userId","messageTarget":"100184270","connectionId":"CjzZpfFSIAMCFFQ="}

LOG 2023-06-19T02:21:28.977Z
      Empting callback queue list

LOG 2023-06-19T02:21:28.976Z
      Empting callback queue list

LOG 2023-06-19T02:21:28.339Z
      character_sheet_changed
      {"passivePerception":11,"passi
```

**Comment by Azmoria** [comment]
Doing some clean up of older issues. 

This particular one may have been the DM having deleted the player scene at the time without selecting a new one, or a blip in the server. A message was added awhile back to inform players to ask their DM to click the player button on a scene to resolve this if not a server blip.
