### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by jackie-entelect** [cyruzzo/AboveVTT#1273]
**Error:**
```
TypeError: Cannot read properties of undefined (reading 'startsWith')
Failed to start AboveVTT on https://www.dndbeyond.com/characters/95462269?abovevtt=true
Error: TypeError: Cannot read properties of undefined (reading 'startsWith')
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:297:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:51:9
```
**Environment:**
```
{"avttVersion":"0.96","browser":{"name":"Chrome","version":"114","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-06-24T05:58:13.109Z
      STARTING MB WITH TOKEN

LOG 2023-06-24T05:58:13.108Z
      LOADING WS: There Are 0 elements in the queue

LOG 2023-06-24T05:58:13.107Z
      TOKEN IS CACHED

LOG 2023-06-24T05:58:13.100Z
      startup_step Creating StatHandler, PeerManager, and MessageBroker

LOG 2023-06-24T05:58:13.099Z
      startup_step Fetching token customizations

LOG 2023-06-24T05:58:12.883Z
      startup_step Fetching config data from DDB

LOG 2023-06-24T05:58:12.097Z
      Babylon.js v6.3.0 - WebGL2 - Parallel shader compilation

LOG 2023-06-24T05:58:08.361Z
      startup_step Gathering player character data

LOG 2023-06-24T05:58:06.976Z
      FFM CONTAINER
      {"release-gate-ims":false,"release-gate.tactical-maps":false,"release-gate-gfs-blessings-ui":false,"release-gate-character-sheet-campaign-settings":false,"release-gate-character-sheet-tour":false,"release-gate-random-name-multiple-suggestions":true,"release-gate-premade-characters":null}

LOG 2023-06-24T05:58:06.901Z
      DDBApi.fetchCampaignInfo

LOG 2023-06-24T05:58:06.900Z
      start_above_vtt_common

LOG 2023-06-24T05:58:06.899Z
      harvest_campaign_secret found it in localStorage

LOG 2023-06-24T05:58:06.899Z
      startup_step Starting AboveVTT for character

LOG 2023-06-24T05:58:06.894Z
      set_avtt_setting_value aggressiveErrorMessages is now false

LOG 2023-06-24T05:58:06.156Z
      FF
```

**Comment by Azmoria** [comment]
I _think_ this is missing permissions. We had to update the permissions to include the video plugin's site that we use. We did this to fix the video a couple versions back.
