### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by ZenVenture** [cyruzzo/AboveVTT#1286]
**Error:**
```
TypeError: Cannot read properties of undefined (reading 'startsWith')
Failed to start AboveVTT on https://www.dndbeyond.com/characters/88114815?abovevtt=true
Error: TypeError: Cannot read properties of undefined (reading 'startsWith')
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:297:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:51:9
```
**Environment:**
```
{"avttVersion":"0.96","browser":{"name":"Chrome","version":"114","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-06-29T22:42:20.819Z
      TOKEN IS CACHED

LOG 2023-06-29T22:42:20.819Z
      LOADING WS: There Are 0 elements in the queue

LOG 2023-06-29T22:42:20.819Z
      STARTING MB WITH TOKEN

LOG 2023-06-29T22:42:20.818Z
      startup_step Creating StatHandler, PeerManager, and MessageBroker

LOG 2023-06-29T22:42:20.817Z
      startup_step Fetching token customizations

LOG 2023-06-29T22:42:20.728Z
      startup_step Fetching config data from DDB

LOG 2023-06-29T22:42:19.931Z
      startup_step Gathering player character data

LOG 2023-06-29T22:42:19.843Z
      Babylon.js v6.3.0 - WebGL2 - Parallel shader compilation

LOG 2023-06-29T22:42:19.574Z
      start_above_vtt_common

LOG 2023-06-29T22:42:19.574Z
      DDBApi.fetchCampaignInfo

LOG 2023-06-29T22:42:19.573Z
      harvest_campaign_secret found it in localStorage

LOG 2023-06-29T22:42:19.573Z
      startup_step Starting AboveVTT for character

LOG 2023-06-29T22:42:19.571Z
      set_avtt_setting_value aggressiveErrorMessages is now false

LOG 2023-06-29T22:42:19.554Z
      FFM CONTAINER
      {"release-gate-ims":false,"release-gate.tactical-maps":false,"release-gate-gfs-blessings-ui":false,"release-gate-character-sheet-campaign-settings":false,"release-gate-character-sheet-tour":false,"release-gate-random-name-multiple-suggestions":true,"release-gate-premade-characters":null}

LOG 2023-06-29T22:42:18.866Z
      DD
```

**Comment by ZenVenture** [comment]
Received this error message when attempting to use AboveVTT ext in chrome browser. No issues in firefox but wanted to expose issue. Any advice on resolution?

**Comment by Azmoria** [comment]
There was someone in discord with the same error yesterday it was an undefined source (url) in the audio mixer. It's possible to clear this if it's the issue.

Pasting `localStorage.removeItem('audio.mixer.[campaignidhere].DM')` replacing `[campaignidhere]` with the id of the campaign for the DM in the dev tools console. You can get the campaign id at the end of the url when viewing the campaign. You can get to the dev tools console with f12 -> console tab -> scroll to the bottom then paste the above.

Similarly for players if that have the same issue replace `DM` with their player id. 

Alternatively clearing the cache should remove the same but it will remove a lot more like my tokens etc.

If this is the issue it should be fixed next release which hopefully will be early next week.

Also double check that the permissions are up to date - but seems more likely the above issue.
