### ISSUE TITLE
DDB API Error: EncounterNotFoundException Encounter does not exist

### ISSUE THREAD

**Issue by Ron-A-R** [cyruzzo/AboveVTT#1308]
**Error:**
```
DDB API Error: EncounterNotFoundException Encounter does not exist
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/acc06752-a836-4612-a3d1-728804ac20d9?abovevtt=true
Error: DDB API Error: EncounterNotFoundException Encounter does not exist
    at lookForErrors (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:36:11)
    at async DDBApi.fetchJsonWithCredentials (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:55:21)
    at async DDBApi.fetchEncounter (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:105:22)
    at async harvest_game_id (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:632:27)
```
**Environment:**
```
{"avttVersion":"0.97","browser":{"name":"Chrome","version":"114","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

ERROR 2023-07-12T15:50:18.333Z
      DDB API Error: EncounterNotFoundException Encounter does not exist

LOG 2023-07-12T15:50:18.276Z
      startup_step Gathering basic campaign info

LOG 2023-07-12T15:50:18.273Z
      startup calling init_splash
```

**Comment by Ron-A-R** [comment]
I was populating the map with tokens and this happened.
