### ISSUE TITLE
register_custom_token_image_context_menu Remove attempted to remove a custom image with an invalid type. listItem:

### ISSUE THREAD

**Issue by Zulbo** [cyruzzo/AboveVTT#1484]
**Error:**
```
register_custom_token_image_context_menu Remove attempted to remove a custom image with an invalid type. listItem:
{"id":"_AboveVTT_Tokens_Overlays_Flame_1","name":"Flame 1","image":"https://thumbs.gfycat.com/GiddyMajorDingo-small.gif","type":"builtinToken","folderPath":"/AboveVTT Tokens/Overlays","parentId":"_AboveVTT_Tokens_Overlays","tokenOptions":{"name":"Flame 1","folderPath":"/Overlays","image":"https://thumbs.gfycat.com/GiddyMajorDingo-small.gif","disableborder":true,"square":true}}
Error: register_custom_token_image_context_menu Remove attempted to remove a custom image with an invalid type. listItem:
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:301:13)
    at S.fn.init.callback (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/TokensPanel.js:2722:29)
    at HTMLLIElement.itemClick (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/jquery.contextMenu.js:915:30)
    at HTMLDocument.dispatch (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/jquery-3.6.0.min.js:2:43064)
    at v.handle (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/jquery-3.6.0.min.js:2:41048)
    at HTMLDocument.r (https://media.dndbeyond.com/encounter-builder/static/js/main.c727c4df.js:2:1301967)
```
**Environment:**
```
{"avttVersion":"0.99.1","browser":{"name":"Chrome","version":"116","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-09-12T07:20:39.295Z
      find_sidebar_list_item
      {"id":"_AboveVTT_Tokens_Overlays_Flame_1","name":"Flame 1","image":"https://thumbs.gfycat.com/GiddyMajorDingo-small.gif","type":"builtinToken","folderPath":"/AboveVTT Tokens/Overlays","parentId":"_AboveVTT_Tokens_Overlays","tokenOptions":{"name":"Flame 1","folderPath":"/Overlays","image":"https://thumbs.gfycat.com/GiddyMajorDingo-small.gif","disableborder":true,"square":true}}

LOG 2023-09-12T07:20:30.569Z
      set_list_item_identifier
      /AboveVTT Tokens/Overlays/Flame 1
    
```

**Comment by Azmoria** [comment]
Doing some clean up of older issues. I believe this was resolved awhile back but if not feel free to reopen as a new issue when it reoccurs.
