### ISSUE TITLE
TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by karjah** [cyruzzo/AboveVTT#1531]
**Error:**
```
TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
Failed to start AboveVTT on https://www.dndbeyond.com/characters/107048656?abovevtt=true
Error: TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:268:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:127:9
```
**Environment:**
```
{"avttVersion":"1.0","browser":{"name":"Chrome","version":"116","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-09-20T17:24:24.422Z
      adjust_site_bar setting width to 100%

LOG 2023-09-20T17:24:24.419Z
      adjust_site_bar setting width to 100%

LOG 2023-09-20T17:24:24.416Z
      adjust_site_bar setting width to 100%

LOG 2023-09-20T17:24:24.412Z
      adjust_site_bar setting width to 100%

LOG 2023-09-20T17:24:24.409Z
      adjust_site_bar setting width to 100%

LOG 2023-09-20T17:24:24.405Z
      adjust_site_bar setting width to 100%

LOG 2023-09-20T17:24:24.376Z
      redraw_settings_panel_token_examples
      undefined

LOG 2023-09-20T17:24:24.350Z
      [audio]
      registering mixer start handler

LOG 2023-09-20T17:24:24.350Z
      [audio]
      initializing audio ui for player

LOG 2023-09-20T17:24:24.347Z
      init_sidebar_tabs

LOG 2023-09-20T17:24:24.347Z
      update_pclist pcs
      [{"senses":[{"name":"Darkvision","distance":"60 ft."}],"proficiencyGroups":[{"group":"Armor","values":""},{"group":"Weapons","values":"Crossbow, Light, Dagger, Dart, Longbow, Longsword, Quarterstaff, Shortbow, Shortsword, Sling"},{"group":"Tools","values":""},{"group":"Languages","values":"Common, Draconic, Dwarvish, Elvish, Goblin"}],"classes":[{"name":"Wizard","level":3,"subclassName":"School of Evocation"}],"proficiencyBonus":2,"resistances":[],"extras":{"creatures":[]},"decorations":{"backdrop":{"largeBackdropAvatar
```

**Comment by Azmoria** [comment]
Doing some clean up of older issues. I believe this was resolved awhile back but if it reoccurs please open a new issue.
