### ISSUE TITLE
Can not export my data - Internal Server Error

### ISSUE THREAD

**Issue by natemoonlife** [cyruzzo/AboveVTT#1538]
**Error:**
```
Internal Server Error
export_scenes failed to fetch from the cloud
Error: Internal Server Error
    at AboveApi.checkForErrors (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/AboveApi.js:52:13)
    at AboveApi.fetchJson (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/AboveApi.js:46:10)
    at async AboveApi.exportScenes (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/AboveApi.js:108:22)
```
**Environment:**
```
{"avttVersion":"1.0.1","browser":{"name":"Chrome","version":"116","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-09-22T01:26:25.437Z
      remove_sidebar_flyout

LOG 2023-09-22T01:26:24.502Z
      [audio]
      user interaction detected, starting mixer

WARN 2023-09-22T01:26:23.322Z
      fetch_monsters failed
      {"readyState":4,"responseText":"{\"errors\":{\"Ids\":[\"The value 'customStat' is not valid.\"]},\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.1\",\"title\":\"One or more validation errors occurred.\",\"status\":400,\"traceId\":\"|e7135238-46cccb1353849ca2.\"}","responseJSON":{"errors":{"Ids":["The value 'customStat' is not valid."]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"|e7135238-46cccb1353849ca2."},"status":400,"statusText":"error"}

LOG 2023-09-22T01:26:23.079Z
      fetch_and_cache_scene_monster_items calling fetch_monsters with ids: 
      ["customStat"]

LOG 2023-09-22T01:26:23.079Z
      fetch_monsters starting with ids
      ["customStat"]

LOG 2023-09-22T01:26:23.079Z
      TOKEN IS CACHED

LOG 2023-09-22T01:26:23.078Z
      fetch_and_cache_scene_monster_items

LOG 2023-09-22T01:26:22.974Z
      iframe pronto..

LOG 2023-09-22T01:26:22.337Z
      set_list_item_identifier
      {"0":{},"length":1}
      /Scenes/yuantitreasure
      migrated2100

LOG 2023-09-22T01:26:22.336Z
      build_sidebar_list_row
      yuantitreasure

LOG 2023-09-22T01:26
```

**Comment by Azmoria** [comment]
I think we resolved this or it may have been a blip but let me know if I'm remembering wrong
