### ISSUE TITLE
DDB API Error: Unknown Error 504 

### ISSUE THREAD

**Issue by all2human** [cyruzzo/AboveVTT#1609]
**Error:**
```
DDB API Error: Unknown Error 504 
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/8ffb37ac-657d-4fd4-b017-8288c1d3d52a?abovevtt=true
Error: DDB API Error: Unknown Error 504 
    at lookForErrors (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:39:11)
    at async DDBApi.fetchJsonWithToken (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:52:21)
    at async DDBApi.fetchConfigJson (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:215:12)
    at async start_above_vtt_common (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:178:26)
    at async start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:200:3)
```
**Environment:**
```
{"avttVersion":"1.1","browser":{"name":"Chrome","version":"117","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

ERROR 2023-10-12T13:26:41.022Z
      DDB API Error: Unknown Error 504 

ERROR 2023-10-12T13:26:41.021Z
      DDBApi.lookForErrors Failed to parse json
      {}
      {}

LOG 2023-10-12T13:25:41.026Z
      startup_step Fetching config data from DDB

LOG 2023-10-12T13:25:40.556Z
      startup_step Gathering player character data

LOG 2023-10-12T13:25:40.377Z
      start_above_vtt_common

LOG 2023-10-12T13:25:40.377Z
      DDBApi.fetchCampaignInfo

LOG 2023-10-12T13:25:40.377Z
      DDBApi is refreshing auth token

LOG 2023-10-12T13:25:40.376Z
      harvest_campaign_secret found it in localStorage

LOG 2023-10-12T13:25:40.376Z
      startup_step Starting AboveVTT for DM
```

**Comment by all2human** [comment]
This cleared up after a while.
