### ISSUE TITLE
promiseRejection undefined

### ISSUE THREAD

**Issue by GamerKing122** [cyruzzo/AboveVTT#1740]
**Error:**
```
promiseRejection undefined

undefined: undefined:undefined

Error: promiseRejection undefined
    at addLog (chrome-extension://ecmhlfifgaghieeolecdeilhgkfiemjh/CoreFunctions.js:72:21)
    at window.onunhandledrejection (chrome-extension://ecmhlfifgaghieeolecdeilhgkfiemjh/CoreFunctions.js:106:7)
```
**Environment:**
```
{"avttVersion":"1.3-beta55","browser":{"name":"Chrome","version":"117","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

PROMISEREJECTION 2023-11-14T13:14:45.684Z
      undefined
      undefined: undefined:undefined
      undefined

LOG 2023-11-14T13:14:42.566Z
      stop deciphering

LOG 2023-11-14T13:14:42.565Z
      injection_id = ddc98fe5-b195-430e-a6d6-dfe56b01f0a87

LOG 2023-11-14T13:14:42.565Z
      injection_data = [object Object]

LOG 2023-11-14T13:14:42.565Z
      TROVATOOOOOOOOOOOOOOOOO

LOG 2023-11-14T13:14:42.563Z
      TROVATOOOOOOOOOOOOOOOOO

LOG 2023-11-14T13:14:42.562Z
      injection_id = db828f52-4895-4e1a-9bf4-f9422d49f1391

LOG 2023-11-14T13:14:42.562Z
      injection_data = [object Object]

LOG 2023-11-14T13:14:42.561Z
      deciphering

LOG 2023-11-14T13:14:42.348Z
      dice/roll/pending

LOG 2023-11-14T13:14:42.185Z
      custom/myVTT/whatsyourdicerolldefault

LOG 2023-11-14T13:14:42.137Z
      custom/myVTT/hidemydicestream

LOG 2023-11-14T13:14:41.687Z
      custom/myVTT/iceforyourgintonic

LOG 2023-11-14T13:14:41.672Z
      custom/myVTT/iceforyourgintonic

LOG 2023-11-14T13:14:41.591Z
      custom/myVTT/iceforyourgintonic

LOG 2023-11-14T13:14:41.557Z
      custom/myVTT/iceforyourgintonic

LOG 2023-11-14T13:14:41.522Z
      fatto setLocalDescription

LOG 2023-11-14T13:14:41.513Z
      aggiungo video!!!!

LOG 2023-11-14T13:14:41.510Z
      fatto setRemoteDescription

LOG 2023-11-14T13:14:41.508Z
      custom/myVTT/okletmeseeyourdice

LOG 2023-11-14T13:14:40.229Z
      showErrorMessage
      undefined
      undefined: undefined:undefined
      undefined
      {}

```

**Comment by Azmoria** [comment]
Doing some clean up of older issues. I believe this was resolved - if not please open a new report when the error reoccurs so we can get some updated data that matches the current version.
