### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by dstidolph1** [cyruzzo/AboveVTT#1787]
**Error:**
```
Internal Server Error
export_scenes failed to fetch from the cloud
Error: Internal Server Error
    at AboveApi.checkForErrors (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/AboveApi.js:52:13)
    at AboveApi.fetchJson (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/AboveApi.js:46:10)
    at async AboveApi.exportScenes (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/AboveApi.js:108:22)
```
**Environment:**
```
{"avttVersion":"1.3.1","browser":{"name":"Chrome","version":"119","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2023-12-02T15:09:21.073Z
      remove_sidebar_flyout

LOG 2023-12-02T15:09:08.656Z
      showErrorMessage
      export_scenes failed to fetch from the cloud
      {}

LOG 2023-12-02T15:08:52.378Z
      remove_sidebar_flyout

LOG 2023-12-02T15:08:50.330Z
      [audio]
      user interaction detected, starting mixer

LOG 2023-12-02T15:08:48.130Z
      fetch_monsters succeeded

LOG 2023-12-02T15:08:47.736Z
      configure_peer_manager_from_settings

LOG 2023-12-02T15:08:47.736Z
      disable_peer_manager

LOG 2023-12-02T15:08:47.736Z
      stop_sending_cursor_to_peers

LOG 2023-12-02T15:08:47.182Z
      fetch_and_cache_scene_monster_items

LOG 2023-12-02T15:08:47.182Z
      fetch_and_cache_scene_monster_items calling fetch_monsters with ids: 
      [17062,16871,17118,175346]

LOG 2023-12-02T15:08:47.182Z
      fetch_monsters starting with ids
      [17062,16871,17118,175346]

LOG 2023-12-02T15:08:47.182Z
      TOKEN IS CACHED

LOG 2023-12-02T15:08:46.772Z
      build_sidebar_list_row
      Yuan-Ti Lair

LOG 2023-12-02T15:08:46.772Z
      set_list_item_identifier
      {"0":{},"length":1}
      /Scenes/Eagle's Rock/Yuan-Ti Lair
      ceb77e91-49a2-4729-aaeb-3ec501fbed26

LOG 2023-12-02T15:08:46.771Z
      build_sidebar_list_row
      Xanathar Guild Hideout

LOG 2023-12-02T15:08:46.771Z
      set_list_item_identifier
      {"0":{},"length":1}
      /Scenes/Prewritten/X
```

**Comment by sanderwill** [comment]
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 


java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
 at org.nlogo.agent.Patch.setPatchVariable(Patch.java:242)
 at org.nlogo.agent.Turtle.setPatchVariable(Turtle.java:527)
 at org.nlogo.prim._asm_procedurego_setpatchvariable_13.perform(:1)
 at org.nlogo.nvm.Context.runExclusive(Context.java:133)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:177)
 at org.nlogo.prim._asm_procedurego_ask_9.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.3.0
main: org.nlogo.app.AppFrame
thread: JobThread
OpenJDK 64-Bit Server VM 17.0.4 (BellSoft; 17.0.4+8-LTS)
operating system: Mac OS X 10.15.7 (x86_64 processor)
Scala version 2.12.16
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

11:23:41.935 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
11:23:41.935 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
11:23:41.883 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:23:41.882 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
11:23:41.864 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:23:41.864 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:23:41.864 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:23:41.663 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:23:41.663 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:23:41.663 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
