### ISSUE TITLE
Unable to render a DDB chapter. This url does not appear to be a valid DDB chapter https://www.dndbeyond.com/claim/source/prisoner-13

### ISSUE THREAD

**Issue by JayODraco5harp** [cyruzzo/AboveVTT#1812]
**Error:**
```
Unable to render a DDB chapter. This url does not appear to be a valid DDB chapter https://www.dndbeyond.com/claim/source/prisoner-13

Error: Unable to render a DDB chapter. This url does not appear to be a valid DDB chapter https://www.dndbeyond.com/claim/source/prisoner-13
    at render_source_chapter_in_iframe (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Journal.js:1783:13)
    at HTMLDivElement.<anonymous> (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Journal.js:461:7)
    at HTMLDivElement.dispatch (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/jquery-3.6.0.min.js:2:43064)
    at v.handle (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/jquery-3.6.0.min.js:2:41048)
    at HTMLDivElement.r (https://media.dndbeyond.com/encounter-builder/static/js/main.c727c4df.js:2:1301967)</anonymous>
```
**Environment:**
```
{"avttVersion":"1.4","browser":{"name":"Chrome","version":"120","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

ERROR 2024-01-03T02:10:33.456Z
      render_source_chapter_in_iframe was given an invalid url
      https://www.dndbeyond.com/claim/source/prisoner-13

LOG 2024-01-03T02:10:32.378Z
      xxx

LOG 2024-01-03T02:10:32.375Z
      xxx

LOG 2024-01-03T02:10:32.370Z
      no.... non scansiono

LOG 2024-01-03T02:10:32.350Z
      scansiono p13

LOG 2024-01-03T02:10:21.526Z
      render_source_chapter_in_iframe is loading https://www.dndbeyond.com/claim/source/prisoner-13
      {"0":{},"length":1}
      {}

LOG 2024-01-03T02:10:18.283Z
      find_or_create_generic_draggable_window id: sourceChapterIframe_resizeDrag, titleBarText: Source Book, addLoadingIndicator: true, addPopoutButton: true

LOG 2024-01-03T02:10:18.273Z
      showErrorMessage
      {}

ERROR 2024-01-03T02:10:18.270Z
      render_source_chapter_in_iframe was given an invalid url
      https://www.dndbeyond.com/claim/source/prisoner-13

LOG 2024-01-03T02:10:14.207Z
      render_source_chapter_in_iframe
```

**Comment by Azmoria** [comment]
Fixed awhile back - closing
