### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'channels')

### ISSUE THREAD

**Issue by Sighmaster** [cyruzzo/AboveVTT#2112]
**Error:**
```
TypeError: Cannot read properties of undefined (reading 'channels')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/615bf46d-9ece-4825-8870-7ee344e1a02c?abovevtt=true
Error: TypeError: Cannot read properties of undefined (reading 'channels')
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:381:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:179:9
```
**Environment:**
```
{"avttVersion":"1.13","browser":{"name":"Chrome","version":"124","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-05-04T03:32:46.733Z
      is video? false

LOG 2024-05-04T03:32:46.724Z
      SETTO BACKGROUND A [object Object]

LOG 2024-05-04T03:32:46.722Z
      migrate_scene_folders pathsWithoutFolders
      []

LOG 2024-05-04T03:32:46.721Z
      migrate_scene_folders MB
      {"mysenderid":"394399cb-692a-40dd-a16f-668565edc4ba","stats":{"reflected":0,"peers":{}},"above_sequence":2,"chat_id":"ae9fcb0d-11d1-4f10-a2b3-8c6137fcb089","chat_counter":0,"chat_pending_messages":[],"chat_message_history":[],"chat_decipher_task":null,"callbackQueue":[],"callbackAboveQueue":[],"userid":"120292473","gameid":"5367446","url":"wss://game-log-api-live.dndbeyond.com/v1","diceMessageSelector":"tss-r93asv-RollType","origRequestAnimFrame":null,"lastAlertTS":0,"latestVersionSeen":"1.13","loadingWS":false,"ws":{},"abovews":{},"loadingAboveWS":false}

LOG 2024-05-04T03:32:46.720Z
      AboveApi.getScene(97ecada6-7676-45ac-b49f-0f7fed0c0fd1)
      {"objectId":"scenes#97ecada6-7676-45ac-b49f-0f7fed0c0fd1#scenedata","campaignId":"[REDACTED]","sceneId":"97ecada6-7676-45ac-b49f-0f7fed0c0fd1","data":{"itemType":"scene","scaleAdjustment":{"x":1,"y":1},"reveals":[[0,0,0,0,2,0],[523,255,0,0,0,0,1],[518,277,0,0,0,0,1]],"gridStrokeNumberInput":"0.5","scale":66.66666666666666,"vpps":81.9,"darkness_filter_number":"0","title":"C00-00 Voyage","fog_of_war":"1","uuid":"","player_map":"
```

**Comment by Azmoria** [comment]
Haven't seen this for awhile closing for now - can be reopened with new report if still occuring
