### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by BastHardo** [cyruzzo/AboveVTT#2184]
Why do I get this problem

**Error:**
```
TypeError: Failed to fetch
Failed to start AboveVTT on https://www.dndbeyond.com/characters/119771466?abovevtt=true
Error: TypeError: Failed to fetch
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:440:13)
    at chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:195:9
```
**Environment:**
```
{"avttVersion":"1.15","browser":{"name":"Chrome","version":"122","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

ERROR 2024-05-21T10:22:09.071Z
      Failed to get messages
      {}

LOG 2024-05-21T10:21:39.366Z
      Babylon.js v6.3.0 - WebGL2 - Parallel shader compilation

LOG 2024-05-21T10:21:38.668Z
      startup_step Gathering player character data

LOG 2024-05-21T10:21:36.471Z
      DDBApi.fetchCampaignInfo

LOG 2024-05-21T10:21:36.470Z
      start_above_vtt_common

LOG 2024-05-21T10:21:36.463Z
      startup_step Starting AboveVTT for character

LOG 2024-05-21T10:21:36.462Z
      harvest_campaign_secret found it in localStorage
```

**Comment by Azmoria** [comment]
It's a generic error when something doesn't get sent down by a server (I think either ours or ddbs). Most of the time a refresh fixes it. 

As a player it could be the DM deleted the map you were last on and didn't set a new map for the players. So it could be requesting a scene that doesn't exist. 

If it happens every load and the above isn't the cause there may be another issue I'm unaware of.
