### ISSUE TITLE
Constant Websocket Reconnects

### ISSUE THREAD

**Issue by SleepySloth47** [cyruzzo/AboveVTT#2278]
**Error:**
```
Failed to fetch
Failed to start AboveVTT on https://www.dndbeyond.com/characters/118504292?abovevtt=true
TypeError: Failed to fetch
    at https://analytics.tiktok.com/i18n/pixel/static/main.MTU0NDc1MDUxMA.js:2:171345
    at new Promise (<anonymous>)
    at fetch (https://analytics.tiktok.com/i18n/pixel/static/main.MTU0NDc1MDUxMA.js:2:171301)
    at AboveApi.fetchJson (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/AboveApi.js:44:27)
    at AboveApi.getCurrentScene (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/AboveApi.js:69:33)
    at start_above_vtt_for_players (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:466:43)</anonymous>
```
**Environment:**
```
{"avttVersion":"1.19","browser":{"name":"Chrome","version":"126","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

ERROR 2024-06-23T00:56:27.875Z
      MB.onerror
      {"isTrusted":true}

LOG 2024-06-23T00:56:25.823Z
      debounce_fetch_character_from_api is about to call update_pc_with_data with
      118506396
      {"senses":[],"proficiencyGroups":[{"group":"Armor","values":""},{"group":"Weapons","values":"Crossbow, Light, Dagger, Dart, Quarterstaff, Sling"},{"group":"Tools","values":"Playing Card Set"},{"group":"Languages","values":"Common, Dwarvish"}],"classes":[{"name":"Wizard","level":2,"subclassName":"School of Evocation"}],"proficiencyBonus":2,"resistances":[],"extras":{"creatures":[]},"decorations":{"backdrop":{"largeBackdropAvatarUrl":"https://www.dndbeyond.com/avatars/61/558/636453169377593443.jpeg","smallBackdropAvatarUrl":"https://www.dndbeyond.com/avatars/61/557/636453169376963233.jpeg","backdropAvatarUrl":"https://www.dndbeyond.com/avatars/61/556/636453169376650613.jpeg","thumbnailBackdropAvatarUrl":"https://www.dndbeyond.com/avatars/61/559/636453169378067426.jpeg"},"characterTheme":{"name":"DDB Red","isDarkMode":false,"isDefault":true,"backgroundColor":"#FEFEFE","themeColor":"#C53131"},"avatar":{"avatarUrl"
```

**Comment by Azmoria** [comment]
The most common cause of constant reconnects is VPNs or other extensions/programs. It could also be settings on a router or modem especially school/work networks.

Unfortunately it's mostly guess and check until the problem piece can be found. Some quick ways to narrow it down - try another browser preferably without other extensions will eliminate browser settings and other extensions. 

Temporarily disable any firewall/antivirus (if it's these you may need to whitelist the websocket address). 

If possible try a different device/network - possibly using a phone as a hotspot to see if it's device/network settings.

---

As for the 'Failed to fetch' error, if this is only happening at the start when loading is sometimes just a blip and refreshing usually fixes it. It's a generic error when anything can't be retrieved from a server.

**Comment by Azmoria** [comment]
Closing this for now - just doing some clean up of duplicates/unable to fix stuff.

If you're still experiencing this after looking at some of the above, try enabling auto reconnect in the settings. It may be due to an unstable connection like wireless 4g internet. 

Feel free to reopen with a new report if it's still occurring after that. 

This particular report seems to be happening for a tiktok fetch which is something DDB is calling rather than us. Although the MB error could be on our end still.
