### ISSUE TITLE
Tried to copy and paste a Player's character sheet into a custom stat block, and killed my account 

### ISSUE THREAD

**Issue by wolpht** [cyruzzo/AboveVTT#2317]
After copying and pasting a statblock into a dummy icon in my custom creatures, my account across all my campaigns started showing this error.

**Error:**
```
Maximum call stack size exceeded
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/f26b507b-010e-4900-9e25-36587e56be4c?abovevtt=true
RangeError: Maximum call stack size exceeded
    at get [Symbol.species] (<anonymous>)
    at Array.slice (<anonymous>)
    at JournalManager.sendNotes (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Journal.js:73:31)
    at JournalManager.sendNotes (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Journal.js:76:14)
    at JournalManager.sendNotes (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Journal.js:76:14)
    at JournalManager.sendNotes (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Journal.js:76:14)
    at JournalManager.sendNotes (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Journal.js:76:14)
    at JournalManager.sendNotes (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Journal.js:76:14)
    at JournalManager.sendNotes (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Journal.js:76:14)
    at JournalManager.sendNotes (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Journal.js:76:14)</anonymous></anonymous>
```
**Environment:**
```
{"avttVersion":"1.20","browser":{"name":"Chrome","version":"126","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-07-18T22:24:15.581Z
      build_journal

LOG 2024-07-18T22:24:15.558Z
      [audio]
      registering mixer start handler

LOG 2024-07-18T22:24:15.558Z
      [audio]
      binding mixer to message bus

LOG 2024-07-18T22:24:15.558Z
      [audio]
      initializing audio ui for DM

LOG 2024-07-18T22:24:15.557Z
      init_scenes_panel

LOG 2024-07-18T22:24:15.556Z
      monster_search_filters
      {"challengeRatingMin":23,"monsterTypes":[1,13]}

LOG 2024-07-18T22:24:15.553Z
      TOKEN IS CACHED

LOG 2024-07-18T22:24:15.544Z
      migrate_token_customizations has already completed

LOG 2024-07-18T22:24:15.543Z
      migrate_token_customizations starting to migrate mytokenfolders customizations

LOG 2024-07-18T22:24:15.543Z
      migrate_token_customizations finished migrating mytokenfolders customizations

LOG 2024-07-18T22:24:15.543Z
      migrate_token_customizations starting to migrate mytokens customizations

LOG 2024-07-18T22:24:15.543Z
      migrate_token_customizations finished migrating mytokens customizations

LOG 2024-07-18T22:24:15.540Z
      init_sidebar_tabs

LOG 2024-07-18T22:24:15.540Z
      init_tokens_panel

LOG 2024-07-18T22:24:15.388Z
      init_ui

LOG 2024-07-18T22:24:15.387Z
      DDBApi.fetchAllEncounters attempting to fetch pages 2 through 1

LOG 2024-07-18T22:24:15.387Z
      startup_step Setting up UI

LOG 2024-07-18T22:24:15.157Z
      AboveApi.getSceneList
      [{"objectId":"scenes#013b5a68-bef5-4e7b-9eef-e86c0688083e#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","reveals":[],"gridStrokeNumberInput":"0.5","scale":"100","vpps":60,"darkness_filter_number":"0","title":"mines Lower Level","fog_of_war":"1","uuid":"","player_map":"https://dl.dropboxusercontent.com/scl/fi/i59hb46sejwlx0v5b64lk/Mithril-mines-2.png?rlkey=je5p4onf869u0p5imia8m8c0c&st=mhdalz81&dl=0","upsq":"ft","folderPath":"/maps","playlist":"0","gridType":1,"drawings":[],"fpsq":"5","tokens":{},"id":"013b5a68-bef5-4e7b-9eef-e86c0688083e","darkness_filter":"0","grid_line_width":"0.5","order":1717264131410,"parentId":"a4a4b243-565f-4507-bce6-c98539555e49","scale_factor":"","offsetx":0,"dm_map_usable":"0","offsety":0,"dm_map_is_video":"0","grid":"0","scale_check":true,"dm_map":"","player_map_is_video":"0","hpps":60,"disableSceneVision":"0","visionTrail":"0","grid_color":"rgba(0, 0, 0, 0.5)","snap":"0"},"sceneId":"013b5a68-bef5-4e7b-9eef-e86c0688083e"},{"objectId":"scenes#01ab861c-8b3d-4468-9b17-eaa57b38bfa1#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","reveals":[],"gridStrokeNumberInput":"0.5","scale":50,"vpps":44.1,"darkness_filter_number":"0","title":"1f ground","fog_of_war":"1","uuid":"","player_map":"https://drive.google.com/thumbnail?id=1pjqI53aI0cYeejU-yCfAkRuurwpzmy0R&sz=w3000","upsq":"ft","folderPath":"","scaleX":0.5,"scaleY":0.5,"isnewscene":false,"gridType":"1","drawings":[],"fpsq":"1","tokens":{},"id":"01ab861c-8b3d-4468-9b17-eaa57b38bfa1","darkness_filter":"0","grid_line_width":"0.5","order":1702597107496,"grid_subdivided":"0","parentId":"scenesFolder","scale_factor":2,"offsetx":0,"dm_map_usable":"0","offsety":119.59999999999997,"dm_map_is_video":"0","grid":"1","scale_check":true,"dm_map":"","player_map_is_video":"0","hpps":45,"disableSceneVision":"0","grid_color":"rgba(0, 0, 0, 0.5)","snap":"0"},"sceneId":"01ab861c-8b3d-4468-9b17-eaa57b38bfa1"},{"objectId":"scenes#1ff01f69-5ef1-4b8a-b13b-00b1a5206361#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","reveals":[],"gridStrokeNumberInput":"0.5","scale":"100","vpps":60,"darkness_filter_number":"0","title":"Dagon","fog_of_war":"1","uuid":"","player_map":"https://dl.dropboxusercontent.com/scl/fi/0hut2axcm37m1x2dfuf3p/Dagon.png?rlkey=mu3wmmb7cymf3ydkvvw91gmtc&dl=0","upsq":"ft","folderPath":"/Boss monsters","playlist":"0","gridType":1,"drawings":[],"fpsq":"5","tokens":{},"id":"1ff01f69-5ef1-4b8a-b13b-00b1a5206361","darkness_filter":"0","grid_line_width":"0.5","order":1712795839072,"parentId":"62db8768-7de9-4949-a694-c6725ccdc5c9","scale_factor":"","offsetx":0,"dm_map_usable":"0","offsety":0,"dm_map_is_video":"0","grid":"0","scale_check":true,"dm_map":"","player_map_is_video":"0","hpps":60,"disableSceneVision":"0","grid_color":"rgba(0, 0, 0, 0.5)","snap":"0"},"sceneId":"1ff01f69-5ef1-4b8a-b13b-00b1a5206361"},{"objectId":"scenes#2643b57d-9fb1-43a9-936c-d8d942aab92d#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","thumb":"https://media.dndbeyond.com/compendium-images/sacoc/zBbqVwSoOPBn2DCM/00-002.strixhaven-university.jpg","reveals":[],"scale":"100","vpps":60,"title":"Strixhaven University, with the (Center) Biblioplex Surrounded by (Top) Silverquilland (Going Clockwise) Quandrix, Witherbloom, Prismari, and Lorehold","fog_of_war":"1","uuid":"sacoc/welcome-to-strixhaven/imguniversity","player_map":"https://media.dndbeyond.com/compendium-images/sacoc/zBbqVwSoOPBn2DCM/00-002.strixhaven-university.jpg","upsq":"ft","folderPath":"","drawings":[],"fpsq":5,"tokens":{},"id":"2643b57d-9fb1-43a9-936c-d8d942aab92d","darkness_filter":"0","order":1679935305522,"parentId":"scenesFolder","offsetx":0,"dm_map_usable":"0","offsety":0,"dm_map_is_video":"0","grid":0,"dm_map":"","player_map_is_video":"0","hpps":60,"snap":0},"sceneId":"2643b57d-9fb1-43a9-936c-d8d942aab92d"},{"objectId":"scenes#2c39aa16-ea44-4bcd-aeb2-82087e55db1e#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","reveals":[],"gridStrokeNumberInput":"0.5","scale":"100","vpps":60,"darkness_filter_number":"0","title":"Karl (Primordial's Avatar)","fog_of_war":"1","uuid":"","player_map":"https://dl.dropboxusercontent.com/scl/fi/419yghd4hgts9z70d57w2/Karl-Primordial-Avatar.jpg?rlkey=0xud57s82fht7bvurnv5obry8&dl=0","upsq":"ft","folderPath":"/Boss monsters","playlist":"0","gridType":1,"drawings":[],"fpsq":"5","tokens":{},"id":"2c39aa16-ea44-4bcd-aeb2-82087e55db1e","darkness_filter":"0","grid_line_width":"0.5","order":1712795192138,"parentId":"62db8768-7de9-4949-a694-c6725ccdc5c9","scale_factor":"","offsetx":0,"dm_map_usable":"0","offsety":0,"dm_map_is_video":"0","grid":"0","scale_check":true,"dm_map":"","player_map_is_video":"0","hpps":60,"disableSceneVision":"0","grid_color":"rgba(0, 0, 0, 0.5)","snap":"0"},"sceneId":"2c39aa16-ea44-4bcd-aeb2-82087e55db1e"},{"objectId":"scenes#5b683e17-052e-493d-bbf9-60b7dabb78b3#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","reveals":[],"gridStrokeNumberInput":"0.5","scale":92.3076923076923,"vpps":"52.99999999999999","darkness_filter_number":"100","title":"The Chasm","fog_of_war":"1","uuid":"","player_map":"https://dl.dropboxusercontent.com/scl/fi/d82rngbpldmst2hx3dsup/the-chasm.png?rlkey=gku4wrfbt4f9r22wu12hb3jdd&st=gx70skqp&dl=0","upsq":"ft","folderPath":"/maps","scaleX":0.9230769230769231,"scaleY":1.1320754716981132,"isnewscene":false,"playlist":"0","gridType":"1","drawings":[],"fpsq":"40","tokens":{},"id":"5b683e17-052e-493d-bbf9-60b7dabb78b3","darkness_filter":"100","grid_line_width":"0.5","order":1717264212387,"grid_subdivided":"0","parentId":"a4a4b243-565f-4507-bce6-c98539555e49","scale_factor":"2","offsetx":"2.999999999999929","dm_map_usable":"0","offsety":"19","dm_map_is_video":"0","grid":"1","scale_check":true,"dm_map":"","player_map_is_video":"0","hpps":"57.91428571428571","disableSceneVision":"0","visionTrail":"0","grid_color":"black","snap":"1"},"sceneId":"5b683e17-052e-493d-bbf9-60b7dabb78b3"},{"objectId":"scenes#62db8768-7de9-4949-a694-c6725ccdc5c9#scenedata","campaignId":"[REDACTED]","data":{"itemType":"folder","reveals":[],"vpps":null,"title":"Boss monsters","parentId":"scenesFolder","player_map":"","folderPath":"/Scenes","offsetx":null,"offsety":null,"drawings":[],"scale_check":true,"dm_map":"","tokens":{},"id":"62db8768-7de9-4949-a694-c6725ccdc5c9","hpps":null},"sceneId":"62db8768-7de9-4949-a694-c6725ccdc5c9"},{"objectId":"scenes#666#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","reveals":[],"scale":"100","vpps":"72","title":"The Tavern","fog_of_war":"1","parentId":"scenesFolder","player_map":"https://i.pinimg.com/originals/a2/04/d4/a204d4a2faceb7f4ae93e8bd9d146469.jpg","upsq":"ft","offsetx":29,"dm_map_usable":"0","offsety":54,"dm_map_is_video":"0","drawings":[],"grid":"0","dm_map":"","player_map_is_video":"0","fpsq":"5","tokens":{},"id":"666","hpps":"72","snap":"1","order":1000000},"sceneId":"666"},{"objectId":"scenes#6f65755a-4252-4245-a0d8-90b5ff8b1f2e#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","reveals":[],"scale":"100","vpps":60,"title":"The Grand Hall (16x24)","fog_of_war":"1","player_map":"https://dl.dropboxusercontent.com/scl/fi/2aw2ynv8rsoizjskcmt79/The-Grand-Hall-16x24.jpg?rlkey=wblc79sgkv1i09y634farkrwd&dl=0","upsq":"ft","folderPath":"","gridType":1,"drawings":[],"fpsq":5,"tokens":{},"id":"6f65755a-4252-4245-a0d8-90b5ff8b1f2e","darkness_filter":"0","order":1715285964135,"parentId":"scenesFolder","offsetx":0,"dm_map_usable":"0","offsety":0,"dm_map_is_video":"0","grid":0,"dm_map":"","player_map_is_video":"0","hpps":60,"snap":0},"sceneId":"6f65755a-4252-4245-a0d8-90b5ff8b1f2e","timestamp":1715285966552},{"objectId":"scenes#80d4a791-abce-4c0e-86c1-3a93a90c9994#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","reveals":[],"gridStrokeNumberInput":"0.5","scale":"100","vpps":60,"darkness_filter_number":"0","title":"Diedra","fog_of_war":"1","uuid":"","player_map":"https://dl.dropboxusercontent.com/scl/fi/hc7fo87jhskgrk2tscpyc/Diedra.png?rlkey=rpyltq0o08sgx205iwuwg5thd&dl=0","upsq":"ft","folderPath":"/Boss monsters","playlist":"0","gridType":1,"drawings":[],"fpsq":"5","tokens":{},"id":"80d4a791-abce-4c0e-86c1-3a93a90c9994","darkness_filter":"0","grid_line_width":"0.5","order":1712795361836,"parentId":"62db8768-7de9-4949-a694-c6725ccdc5c9","scale_factor":"","offsetx":0,"dm_map_usable":"0","offsety":0,"dm_map_is_video":"0","grid":"0","scale_check":true,"dm_map":"","player_map_is_video":"0","hpps":60,"disableSceneVision":"0","grid_color":"rgba(0, 0, 0, 0.5)","snap":"0"},"sceneId":"80d4a791-abce-4c0e-86c1-3a93a90c9994"},{"objectId":"scenes#8a7999fa-a69d-46fc-a822-e026a659cd7d#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","scaleAdjustment":{"x":1,"y":1},"reveals":[],"gridStrokeNumberInput":"0.5","scale":272.7272727272727,"vpps":56.16,"darkness_filter_number":"100","title":"Necroplis","fog_of_war":"1","uuid":"","player_map":"https://dl.dropboxusercontent.com/scl/fi/hyh03nrg3alqktq2jbs2h/Necroplis-at-Telamok.png?rlkey=q1a9jz5fy0mqgi320hnjvrjup&st=ocjhgfeq&dl=0","upsq":"ft","folderPath":"/maps","scaleX":2.727272727272727,"scaleY":2.608695652173913,"isnewscene":false,"playlist":"0","gridType":"1","drawings":[],"fpsq":"25","tokens":{},"id":"8a7999fa-a69d-46fc-a822-e026a659cd7d","darkness_filter":"100","grid_line_width":"0.5","order":1717264271706,"grid_subdivided":"0","parentId":"a4a4b243-565f-4507-bce6-c98539555e49","scale_factor":1,"offsetx":17,"dm_map_usable":"0","offsety":4.000000000000071,"dm_map_is_video":"0","grid":"1","scale_check":true,"dm_map":"","player_map_is_video":"0","hpps":71.9,"disableSceneVision":"0","visionTrail":"0","grid_color":"#6fa8dc","snap":"0"},"sceneId":"8a7999fa-a69d-46fc-a822-e026a659cd7d"},{"objectId":"scenes#93f4f21e-6396-4aee-92d6-315839eb319f#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","reveals":[],"scale":"100","vpps":60,"title":"The Grand Hall (16x24)","fog_of_war":"1","player_map":"https://dl.dropboxusercontent.com/scl/fi/2aw2ynv8rsoizjskcmt79/The-Grand-Hall-16x24.jpg?rlkey=wblc79sgkv1i09y634farkrwd&dl=0","upsq":"ft","folderPath":"","gridType":1,"drawings":[],"fpsq":5,"tokens":{},"id":"93f4f21e-6396-4aee-92d6-315839eb319f","darkness_filter":"0","order":1715285964136,"parentId":"scenesFolder","offsetx":0,"dm_map_usable":"0","offsety":0,"dm_map_is_video":"0","grid":0,"dm_map":"","player_map_is_video":"0","hpps":60,"snap":0},"sceneId":"93f4f21e-6396-4aee-92d6-315839eb319f","timestamp":1715285966541},{"objectId":"scenes#958cfd12-2e1e-4ca5-b173-68fb7a89507e#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","reveals":[],"gridStrokeNumberInput":"0.5","scale":26.31578947368421,"vpps":"140","darkness_filter_number":"100","title":"From chasm to labrynth","fog_of_war":"1","uuid":"","player_map":"https://dl.dropboxusercontent.com/scl/fi/mu0r0qa8vd6bqaomp5b44/Living-Depths-Pt.1-Corrupted-Dark-61x36-150-DPI.jpg?rlkey=6lhek3j3onnihwxd8p1xobtdl&dl=0","upsq":"ft","folderPath":"/maps","scaleX":0.2631578947368421,"scaleY":0.42857142857142855,"playlist":"0","gridType":"1","drawings":[],"fpsq":"10","tokens":{},"id":"958cfd12-2e1e-4ca5-b173-68fb7a89507e","darkness_filter":"100","grid_line_width":"0.5","order":1720313672401,"grid_subdivided":"0","parentId":"a4a4b243-565f-4507-bce6-c98539555e49","scale_factor":"1","offsetx":"1.6666666666668561","dm_map_usable":"0","offsety":"0","dm_map_is_video":"0","grid":"1","scale_check":true,"dm_map":"","player_map_is_video":"0","hpps":"182.94666278053046","disableSceneVision":"0","visionTrail":"0","grid_color":"black","snap":"1"},"sceneId":"958cfd12-2e1e-4ca5-b173-68fb7a89507e"},{"objectId":"scenes#a4a4b243-565f-4507-bce6-c98539555e49#scenedata","campaignId":"[REDACTED]","data":{"itemType":"folder","reveals":[],"vpps":null,"title":"maps","parentId":"scenesFolder","player_map":"","folderPath":"/Scenes","offsetx":null,"offsety":null,"drawings":[],"scale_check":true,"dm_map":"","tokens":{},"id":"a4a4b243-565f-4507-bce6-c98539555e49","hpps":null},"sceneId":"a4a4b243-565f-4507-bce6-c98539555e49"},{"objectId":"scenes#ba44a721-953b-4833-9a5f-b70b454c3e70#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","thumb":"https://media.dndbeyond.com/compendium-images/vnee/FRZhNxsynhjoMpeh/map-0.01-catacombs.jpg","reveals":[],"gridStrokeNumberInput":"0.5","scale":100,"vpps":"94.66666666666667","darkness_filter_number":"100","title":"Map: Nest of the Eldritch Eye","fog_of_war":"1","uuid":"vnee/vecna-nest-of-the-eldritch-eye/MapNestoftheEldritchEye","player_map":"https://media.dndbeyond.com/compendium-images/vnee/FRZhNxsynhjoMpeh/map-0.01-catacombs-player.jpg","upsq":"ft","folderPath":"/Examples","gridType":1,"drawings":[],"fpsq":"5","tokens":{},"id":"ba44a721-953b-4833-9a5f-b70b454c3e70","darkness_filter":"100","grid_line_width":"0.5","order":1716509791907,"parentId":"d4e3a502-f7b6-492c-b691-a8517f973f37","offsetx":"54.40000000000005","dm_map_usable":"1","offsety":"43.99999999999993","dm_map_is_video":"0","grid":"1","scale_check":true,"dm_map":"https://media.dndbeyond.com/compendium-images/vnee/FRZhNxsynhjoMpeh/map-0.01-catacombs.jpg","player_map_is_video":"0","hpps":"94.8","disableSceneVision":"0","grid_color":"rgba(0, 0, 0, 0.5)","snap":"1"},"sceneId":"ba44a721-953b-4833-9a5f-b70b454c3e70","timestamp":1716509792534},{"objectId":"scenes#c2dac5b9-dbd5-4d00-8ca3-831b959a84aa#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","reveals":[],"gridStrokeNumberInput":"0.5","scale":"100","vpps":60,"darkness_filter_number":"0","title":"Tomb of Illmater","fog_of_war":"1","uuid":"","player_map":"https://dl.dropboxusercontent.com/scl/fi/4b089y7kc8wc57ipnl3h3/tomb-of-xander.png?rlkey=krr4ecprlkfikup6uycjmpu15&st=qgmskl9t&dl=0","upsq":"ft","folderPath":"/maps","playlist":"0","gridType":1,"drawings":[],"fpsq":"5","tokens":{},"id":"c2dac5b9-dbd5-4d00-8ca3-831b959a84aa","darkness_filter":"0","grid_line_width":"0.5","order":1717264376346,"parentId":"a4a4b243-565f-4507-bce6-c98539555e49","scale_factor":"","offsetx":0,"dm_map_usable":"0","offsety":0,"dm_map_is_video":"0","grid":"0","scale_check":true,"dm_map":"","player_map_is_video":"0","hpps":60,"disableSceneVision":"0","visionTrail":"0","grid_color":"rgba(0, 0, 0, 0.5)","snap":"0"},"sceneId":"c2dac5b9-dbd5-4d00-8ca3-831b959a84aa"},{"objectId":"scenes#d4e3a502-f7b6-492c-b691-a8517f973f37#scenedata","campaignId":"[REDACTED]","data":{"itemType":"folder","color":"#F4B459","reveals":[],"vpps":null,"title":"Examples","parentId":"scenesFolder","player_map":"","folderPath":"/Scenes","offsetx":null,"offsety":null,"drawings":[],"scale_check":true,"dm_map":"","tokens":{},"id":"d4e3a502-f7b6-492c-b691-a8517f973f37","hpps":null},"sceneId":"d4e3a502-f7b6-492c-b691-a8517f973f37"},{"objectId":"scenes#d617c8f9-8f4a-493e-86fa-4ebf827f640f#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","reveals":[],"gridStrokeNumberInput":"0.5","scale":100,"vpps":55.10000000000001,"darkness_filter_number":"0","title":"Weapon Factory Ground Floor","fog_of_war":"1","uuid":"","player_map":"https://dl.dropboxusercontent.com/scl/fi/kf64qvdvkjvwt4p0tcgb1/238792.jpg?rlkey=5jetyoqpgqfz6c4lpy94z5h74&dl=0","upsq":"ft","folderPath":"/maps","scaleX":1,"scaleY":1,"isnewscene":false,"playlist":"0","gridType":"1","drawings":[],"fpsq":"5","tokens":{},"id":"d617c8f9-8f4a-493e-86fa-4ebf827f640f","darkness_filter":"0","grid_line_width":"0.5","order":1712791449754,"grid_subdivided":"0","parentId":"a4a4b243-565f-4507-bce6-c98539555e49","scale_factor":2,"offsetx":9.199999999999989,"dm_map_usable":"0","offsety":44.09999999999992,"dm_map_is_video":"0","grid":"1","scale_check":true,"dm_map":"","player_map_is_video":"0","hpps":55.1,"disableSceneVision":"0","grid_color":"rgba(0, 0, 0, 0.5)","snap":"0"},"sceneId":"d617c8f9-8f4a-493e-86fa-4ebf827f640f"},{"objectId":"scenes#d9eda365-0c8f-4894-925e-cc5e22aacae8#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","thumb":"https://64.media.tumblr.com/f75dfb02f5b1ea9faac4ae95456e5bc2/tumblr_pvmo4i6npv1y548mzo1_400.jpg","reveals":[],"scale":100,"vpps":60,"title":"Neutral Party Maps 31","fog_of_war":"1","player_map":"https://64.media.tumblr.com/f75dfb02f5b1ea9faac4ae95456e5bc2/tumblr_pvmo4i6npv1y548mzo1_1280.jpg","upsq":"ft","folderPath":"/maps","gridType":1,"drawings":[],"fpsq":5,"tokens":{},"id":"d9eda365-0c8f-4894-925e-cc5e22aacae8","darkness_filter":"0","order":1712796286029,"parentId":"a4a4b243-565f-4507-bce6-c98539555e49","offsetx":0,"dm_map_usable":"0","offsety":0,"dm_map_is_video":"0","grid":0,"dm_map":"","player_map_is_video":"0","hpps":60,"snap":0},"sceneId":"d9eda365-0c8f-4894-925e-cc5e22aacae8","timestamp":1712796286302},{"objectId":"scenes#ec7c7395-3496-47c2-abd0-71647919f72a#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","reveals":[],"gridStrokeNumberInput":"0.5","scale":"100","vpps":60,"darkness_filter_number":"0","title":"Mines Upper Level","fog_of_war":"1","uuid":"","player_map":"https://dl.dropboxusercontent.com/scl/fi/2c8zekz3o5vvwed798vuv/Mithril-mines-1.png?rlkey=anqncmw05apqy145oq2kxmcqe&st=nfqobw1x&dl=0","upsq":"ft","folderPath":"/maps","playlist":"0","gridType":1,"drawings":[],"fpsq":"5","tokens":{},"id":"ec7c7395-3496-47c2-abd0-71647919f72a","darkness_filter":"0","grid_line_width":"0.5","order":1717264072491,"parentId":"a4a4b243-565f-4507-bce6-c98539555e49","scale_factor":"","offsetx":0,"dm_map_usable":"0","offsety":0,"dm_map_is_video":"0","grid":"0","scale_check":true,"dm_map":"","player_map_is_video":"0","hpps":60,"disableSceneVision":"0","visionTrail":"0","grid_color":"rgba(0, 0, 0, 0.5)","snap":"0"},"sceneId":"ec7c7395-3496-47c2-abd0-71647919f72a"},{"objectId":"scenes#fd5466cc-0722-4e72-a920-f6559e9a7cc8#scenedata","campaignId":"[REDACTED]","data":{"itemType":"scene","gridSubdividedToggle":"0","reveals":[],"gridStrokeNumberInput":"0.5","scale":"100","vpps":"60","darkness_filter_number":"0","title":"Puzzle","fog_of_war":"1","uuid":"","player_map":"https://drive.google.com/thumbnail?id=129dWohzYLZNBziU1wsKU48vuOULl82NY&sz=w3000","upsq":"ft","folderPath":"","drawings":[],"fpsq":"5","tokens":{},"id":"fd5466cc-0722-4e72-a920-f6559e9a7cc8","darkness_filter":"0","grid_line_width":"0.5","order":1680157383942,"grid_subdivided":"","parentId":"scenesFolder","scale_factor":"","offsetx":"0","dm_map_usable":"0","offsety":"0","dm_map_is_video":"0","grid":"0","dm_map":"","player_map_is_video":"0","hpps":"60","grid_color":"rgba(0, 0, 0, 0.5)","snap":"0"},"sceneId":"fd5466cc-0722-4e72-a920-f6559e9a7cc8"}]

LOG 2024-07-18T22:24:15.157Z
      migrate_to_cloud_if_necessary is not necessary

LOG 2024-07-18T22:24:15.157Z
      startup_step Fetching Encounters from DDB

LOG 2024-07-18T22:24:15.157Z
      DDBApi.fetchAllEncounters starting

LOG 2024-07-18T22:24:15.157Z
      DDBApi.fetchAllEncounters attempting to fetch page 1

LOG 2024-07-18T22:24:14.658Z
      Empting callback queue list

LOG 2024-07-18T22:24:14.440Z
      Empting callback queue list

LOG 2024-07-18T22:24:14.232Z
      startup_step Fetching scenes from cloud

LOG 2024-07-18T22:24:14.228Z
      TOKEN IS CACHED

LOG 2024-07-18T22:24:14.228Z
      LOADING WS: There Are 0 elements in the queue

LOG 2024-07-18T22:24:14.228Z
      STARTING MB WITH TOKEN

LOG 2024-07-18T22:24:14.226Z
      startup_step Creating StatHandler, PeerManager, and MessageBroker

LOG 2024-07-18T22:24:14.225Z
      startup_step Fetching token customizations

LOG 2024-07-18T22:24:14.225Z
      fetch_token_customizations starting

LOG 2024-07-18T22:24:14.220Z
      startup_step Fetching config data from DDB

LOG 2024-07-18T22:24:11.409Z
      startup_step Gathering player character data

LOG 2024-07-18T22:24:10.824Z
      start_above_vtt_common

LOG 2024-07-18T22:24:10.824Z
      DDBApi.fetchCampaignInfo

LOG 2024-07-18T22:24:10.824Z
      DDBApi is refreshing auth token

LOG 2024-07-18T22:24:10.823Z
      not showing splash screen
      1.20
      1.20

LOG 2024-07-18T22:24:10.823Z
      harvest_campaign_secret found it in localStorage

LOG 2024-07-18T22:24:10.823Z
      startup_step Starting AboveVTT for DM
```

Help, my game just started T_T

**Comment by wolpht** [comment]
Edit, loaded in opera, and it was operating without my tokens, is there anyway just to get rid of the problem token?

**Comment by Azmoria** [comment]
How much is loaded before this error happens? This is trying to send the journal and stat block to other players. If the token menu  has loaded you should be able to just delete the token/stat block on it. If not removing it will be harder. 

I'll look into why this would be happening as well.

**Comment by Azmoria** [comment]
Just manually forced this error. Pasting this in the console tab of the dev tools should show the token panel. Open the dev tools (generally f12) - click console tab -> scroll to the bottom where `>` is click in beside it and paste the below -> hit enter.

`$('#tokens-panel').css('z-index', '100')`

![image](https://github.com/user-attachments/assets/cc41462f-4d19-4e66-bde6-c11c18af9c05)

**Comment by Azmoria** [comment]
I believe this issue should be resolved in beta now (available on discord). It might still not be able to send that stat block to players if the message size is too large but it shouldn't error in the same way preventing loading.

**Comment by wolpht** [comment]
Thank you so much! I followed your advise and was able to nuke that character out of my icons! You've saved me so much re-working on my campaigns, you rock!
