### ISSUE TITLE
Unable to load scenes from DND Beyond Sources

### ISSUE THREAD

**Issue by mikeb01** [cyruzzo/AboveVTT#2320]
Using the 'Scenes' tab, then 'Create New Scene' I get errors trying to load
- Lightning Keep
- Planescape
- Descent into the Lost Caverns of Tsojcanth

I see the following error in the console:

```
TypeError: Cannot read properties of undefined (reading 'url')
    at ScenesHandler.build_chapters (ScenesHandler.js:715:72)
    at HTMLSelectElement.<anonymous> (ScenesPanel.js:1747:24)
    at HTMLSelectElement.dispatch (VM904 jquery-3.6.0.min.js:2:43064)
    at v.handle (VM904 jquery-3.6.0.min.js:2:41048)
    at Object.trigger (VM904 jquery-3.6.0.min.js:2:71515)
    at HTMLSelectElement.<anonymous> (VM904 jquery-3.6.0.min.js:2:72110)
    at Function.each (VM904 jquery-3.6.0.min.js:2:3003)
    at S.fn.init.each (VM904 jquery-3.6.0.min.js:2:1481)
    at S.fn.init.trigger (VM904 jquery-3.6.0.min.js:2:72086)
    at S.fn.<computed> [as change] (VM904 jquery-3.6.0.min.js:2:88570)
```

**Comment by Azmoria** [comment]
Dndbeyond changes their book urls to includes `/dnd/` and it broke our importer. It's fixed in beta atm.

**Comment by Azmoria** [comment]
Fixed on live
