### ISSUE TITLE
unhandled Error message

### ISSUE THREAD

**Issue by pogowolf** [cyruzzo/AboveVTT#2338]
**Error:**
```
[object Object]

Error: [object Object]
    at showError (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/CoreFunctions.js:444:13)
    at MessageBroker.handleScene (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/MessageBroker.js:1869:4)
```
**Environment:**
```
{"avttVersion":"1.21","browser":{"name":"Chrome","version":"127","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

WARN 2024-08-02T21:45:56.553Z
      Could not find a folder to append scene item to
      {"id":"1c2acd48-d7ab-4943-a8d2-8ac028fc85e1","name":"Lone stone","image":"https://drive.google.com/thumbnail?id=1294UqkSkBdnZMV55uKHEIJThs08voKth&sz=w3000","type":"scene","folderPath":"/Scenes","parentId":"753d9ce4-102b-407f-9bee-0279216328d0","isVideo":false}

LOG 2024-08-02T21:45:56.552Z
      set_list_item_identifier
      {"0":{},"length":1}
      /Scenes/Thingy
      93cc3fec-4be0-490d-8c4f-4194fa9ce079

LOG 2024-08-02T21:45:56.551Z
      build_sidebar_list_row
      Thingy

LOG 2024-08-02T21:45:56.550Z
      build_sidebar_list_row
      Please hold

LOG 2024-08-02T21:45:56.550Z
      set_list_item_identifier
      {"0":{},"length":1}
      /Scenes/Please hold
      ef836a58-68a3-4c3b-aee1-918458438a9b

LOG 2024-08-02T21:45:56.548Z
      set_list_item_identifier
      {"0":{},"length":1}
      /Scenes/New Scene 1
      82e58065-47e9-4c73-9aee-f1d4383bc2c0

LOG 2024-08-02T21:45:56.548Z
      build_sidebar_list_row
      New Scene 2

LOG 2024-08-02T21:45:56.548Z
      set_list_item_identifier
      {"0":{},"length":1}
      /Scenes/New Scene 2
      f52ee01c-7418-405b-8432-239fc10f114e

LOG 2024-08-02T21:45:56.547Z
      build_sidebar_list_row
      New Scene

LOG 2024-08-02T21:45:56.547Z
      set_list_item_identifier
      {"0":{},"length":1}
      /Scenes/New Scene
      66b2b986-6a5c-4b5a-9294-c08aeb2b06b1

LOG 2024-08-02T21:45:56.547Z
      build_sidebar_list_row
      New Scene 1

LOG 2024-08-02T21:45:56.546Z
      build_sideba
```

**Comment by Azmoria** [comment]
Unable to replicate and doesn't have infomation for lines that match our current version code. If it is still occurring please open a new report.
