### ISSUE TITLE
warn undefined

### ISSUE THREAD

**Issue by GamerKing122** [cyruzzo/AboveVTT#2343]
**Error:**
```
warn undefined
character_sheet_observer failed to parse mutation
{}
{}
Error: warn undefined
    at addLog (chrome-extension://fhiappmaahccfoodkdemnpdneejknaad/CoreFunctions.js:73:21)
    at console.warn (chrome-extension://fhiappmaahccfoodkdemnpdneejknaad/CoreFunctions.js:117:9)
    at chrome-extension://fhiappmaahccfoodkdemnpdneejknaad/CharactersPage.js:1377:17
    at Array.forEach (<anonymous>)
    at MutationObserver.<anonymous> (chrome-extension://fhiappmaahccfoodkdemnpdneejknaad/CharactersPage.js:693:18)</anonymous></anonymous>
```
**Environment:**
```
{"avttVersion":"1.22-beta8","browser":{"name":"Chrome","version":"127","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

WARN 2024-08-03T04:18:33.882Z
      character_sheet_observer failed to parse mutation
      {}
      {}

LOG 2024-08-03T04:18:30.375Z
      sendCharacterUpdateEvent

LOG 2024-08-03T04:18:30.332Z
      update_pc character-sheet/character-update/fulfilled
      {"id":"02e373b2-54a6-4587-bc18-d7839bd1fe5c","dateTime":"1722658709661","gameId":"5757292","userId":"110723363","source":"simplified-character-deriver","eventType":"character-sheet/character-update/fulfilled","entityType":"character","entityId":"129040892","persist":false,"messageScope":"gameId","messageTarget":"5757292","data":{"characterId":129040892}}

LOG 2024-08-03T04:18:30.332Z
      update_pc_with_api_call is adding 129040892 to window.PC_NEEDS_API_CALL

LOG 2024-08-03T04:18:30.331Z
      character-sheet/character-update/fulfilled

LOG 2024-08-03T04:18:28.871Z
      character_sheet_changed
      {"decorations":{"characterTheme":{"themeColor":"#972e2e"}}}

LOG 2024-08-03T04:18:28.867Z
      showErrorMessage
      character_sheet_observer failed to parse mutation
      {}
      {}
      Error: warn undefined
    at addLog (chrome-extension://fhiappmaahccfoodkdemnpdneejknaad/CoreFunctions.js:73:21)
    at console.warn (chrome-extension://fhiappmaahccfoodkdemnpdneejknaad/C
```

**Comment by Azmoria** [comment]
Doing some clean up of older issues. I believe this was resolved - if not please open a new report.
