### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by Akuomas** [cyruzzo/AboveVTT#2383]
**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/9dd6904c-b580-493c-9785-56c62f814371?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Chrome","version":"127","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-08-14T18:02:25.219Z
      TOKEN IS CACHED

LOG 2024-08-14T18:02:25.178Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-14T18:02:25.135Z
      build_journal

LOG 2024-08-14T18:02:25.105Z
      [audio]
      binding mixer to message bus

LOG 2024-08-14T18:02:25.105Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-14T18:02:25.104Z
      [audio]
      registering mixer start handler

LOG 2024-08-14T18:02:25.101Z
      init_scenes_panel

LOG 2024-08-14T18:02:25.100Z
      monster_search_filters
      {"search":"wizard"}

LOG 2024-08-14T18:02:25.091Z
      TOKEN IS CACHED

LOG 2024-08-14T18:02:25.080Z
      migrate_token_customizations has already completed

LOG 2024-08-14T18:02:25.079Z
      migrate_token_customizations starting to migrate mytokenfolders customizations

LOG 2024-08-14T18:02:25.079Z
      migrate_token_customizations finished migrating mytokenfolders customizations

LOG 2024-08-14T18:02:25.079Z
      migrate_token_customizations starting to migrate mytokens customizations

LOG 2024-08-14T18:02:25.079Z
      migrate_token_customizations finished migrating mytokens customizations

LOG 2024-08-14T18:02:25.076Z
      init_tokens_panel

LOG 2024-08-14T18:02:25.074Z
      init_sidebar_tabs

LOG 2024-08-14T18:02:24.597Z
      init_ui

LOG 2024-08-14T18:02:24.594Z
      DDBApi.fetchAllEncounters att
```

**Comment by Azmoria** [comment]
The error on load is due to a change ddb made breaking the loading. We are looking for something that is undefined because of it.

You should be able to ignore it for the most part and click close - you'll probably have to reselect a current scene.

I believe this is fixed in beta now, have to do some testing to see if anything else was afffected.

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
