### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by GonzoTinkerman** [cyruzzo/AboveVTT#2384]
**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/40ef7449-73aa-48a5-b6f7-899fab94752a?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Opera"}}
```
**Other Logs:**
```

LOG 2024-08-14T18:50:07.493Z
      TOKEN IS CACHED

LOG 2024-08-14T18:50:07.474Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-14T18:50:07.467Z
      build_journal

LOG 2024-08-14T18:50:07.457Z
      [audio]
      registering mixer start handler

LOG 2024-08-14T18:50:07.457Z
      [audio]
      binding mixer to message bus

LOG 2024-08-14T18:50:07.457Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-14T18:50:07.456Z
      monster_search_filters
      {"search":"tortl"}

LOG 2024-08-14T18:50:07.456Z
      init_scenes_panel

LOG 2024-08-14T18:50:07.454Z
      TOKEN IS CACHED

LOG 2024-08-14T18:50:07.450Z
      migrate_token_customizations starting to migrate mytokenfolders customizations

LOG 2024-08-14T18:50:07.450Z
      migrate_token_customizations finished migrating mytokenfolders customizations

LOG 2024-08-14T18:50:07.450Z
      migrate_token_customizations starting to migrate mytokens customizations

LOG 2024-08-14T18:50:07.450Z
      migrate_token_customizations finished migrating mytokens customizations

LOG 2024-08-14T18:50:07.450Z
      migrate_token_customizations has already completed

LOG 2024-08-14T18:50:07.449Z
      init_tokens_panel

LOG 2024-08-14T18:50:07.448Z
      init_sidebar_tabs

LOG 2024-08-14T18:50:07.399Z
      init_ui

LOG 2024-08-14T18:50:07.398Z
      DDBApi.fetchAllEncounters attempting to fetch pages 2 through 1

LOG 2024-08-14T18:50:07.398Z
      startup_step Settin
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
