### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by Insane96** [cyruzzo/AboveVTT#2385]
**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/f498ddd3-ee5f-4469-a442-ce8541084f3e?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Opera"}}
```
**Other Logs:**
```

LOG 2024-08-14T19:11:48.461Z
      TOKEN IS CACHED

LOG 2024-08-14T19:11:48.409Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-14T19:11:48.387Z
      build_journal

LOG 2024-08-14T19:11:48.326Z
      [audio]
      pushing mixer state to players
      {"paused":false,"channels":{},"playlists":{"c3682ba5-cde0-4045-86f6-f4de60a548a9":{"channels":{},"volume":0.5,"paused":false,"name":"Default"}},"selected":"c3682ba5-cde0-4045-86f6-f4de60a548a9"}

LOG 2024-08-14T19:11:48.320Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-14T19:11:48.319Z
      [audio]
      registering mixer start handler

LOG 2024-08-14T19:11:48.319Z
      [audio]
      binding mixer to message bus

LOG 2024-08-14T19:11:48.317Z
      init_scenes_panel

LOG 2024-08-14T19:11:48.316Z
      monster_search_filters
      {"environments":[9],"search":"spider","sources":[1,104,105,111,113,115,126,136,26,27,3,4,5,62,67,89]}

LOG 2024-08-14T19:11:48.262Z
      build_sidebar_list_row
      Z

LOG 2024-08-14T19:11:48.262Z
      set_list_item_identifier
      /AboveVTT Tokens/Letters/Z
      _AboveVTT_Tokens_Letters_Z

LOG 2024-08-14T19:11:48.261Z
      build_sidebar_list_row
      Y

LOG 2024-08-14T19:11:48.261Z
      set_list_item_identifier
      /AboveVTT Tokens/Letters/Y
      _AboveVTT_Tokens_Letters_Y

LOG 2024-08-14T19:11:48.260Z
      set_list_item_identifier
      /AboveVTT Tokens/Letters/X
      _AboveVTT_Tokens_Letters_X

LOG 2024-08
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
