### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by Ron-A-R** [cyruzzo/AboveVTT#2386]
**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/cb7edb8d-9dde-4719-b283-4860cb4f898e?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Chrome","version":"127","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-08-14T19:58:15.010Z
      TOKEN IS CACHED

LOG 2024-08-14T19:58:14.959Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-14T19:58:14.941Z
      build_journal

LOG 2024-08-14T19:58:14.890Z
      [audio]
      registering mixer start handler

LOG 2024-08-14T19:58:14.890Z
      [audio]
      binding mixer to message bus

LOG 2024-08-14T19:58:14.890Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-14T19:58:14.887Z
      monster_search_filters
      {}

LOG 2024-08-14T19:58:14.887Z
      init_scenes_panel

LOG 2024-08-14T19:58:14.882Z
      TOKEN IS CACHED

LOG 2024-08-14T19:58:14.864Z
      migrate_token_customizations finished migrating mytokenfolders customizations

LOG 2024-08-14T19:58:14.864Z
      migrate_token_customizations starting to migrate mytokens customizations

LOG 2024-08-14T19:58:14.864Z
      migrate_token_customizations finished migrating mytokens customizations

LOG 2024-08-14T19:58:14.864Z
      migrate_token_customizations has already completed

LOG 2024-08-14T19:58:14.863Z
      migrate_token_customizations starting to migrate mytokenfolders customizations

LOG 2024-08-14T19:58:14.861Z
      init_tokens_panel

LOG 2024-08-14T19:58:14.860Z
      init_sidebar_tabs

LOG 2024-08-14T19:58:14.756Z
      init_ui

LOG 2024-08-14T19:58:14.755Z
      DDBApi.fetchAllEncounters successfully fetched
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
