### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by cdmatherly** [cyruzzo/AboveVTT#2387]
**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/305b53ea-ddfd-4c5a-886c-2aff7183c4c2?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Chrome","version":"127","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-08-14T20:04:55.324Z
      TOKEN IS CACHED

LOG 2024-08-14T20:04:55.304Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-14T20:04:55.294Z
      build_journal

LOG 2024-08-14T20:04:55.280Z
      [audio]
      binding mixer to message bus

LOG 2024-08-14T20:04:55.280Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-14T20:04:55.279Z
      [audio]
      registering mixer start handler

LOG 2024-08-14T20:04:55.278Z
      monster_search_filters
      {}

LOG 2024-08-14T20:04:55.278Z
      init_scenes_panel

LOG 2024-08-14T20:04:55.276Z
      TOKEN IS CACHED

LOG 2024-08-14T20:04:55.265Z
      migrate_token_customizations starting to migrate mytokenfolders customizations

LOG 2024-08-14T20:04:55.265Z
      migrate_token_customizations finished migrating mytokenfolders customizations

LOG 2024-08-14T20:04:55.265Z
      migrate_token_customizations starting to migrate mytokens customizations

LOG 2024-08-14T20:04:55.265Z
      migrate_token_customizations finished migrating mytokens customizations

LOG 2024-08-14T20:04:55.265Z
      migrate_token_customizations has already completed

LOG 2024-08-14T20:04:55.264Z
      init_tokens_panel

LOG 2024-08-14T20:04:55.263Z
      init_sidebar_tabs

LOG 2024-08-14T20:04:55.157Z
      init_ui

LOG 2024-08-14T20:04:55.156Z
      DDBApi.fetchAllEncounters attempting to fetch 
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
