### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by vgreis** [cyruzzo/AboveVTT#2389]
**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/d7c39293-e36f-40fa-9d99-f972baa813dc?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Chrome","version":"127","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-08-14T21:27:44.805Z
      TOKEN IS CACHED

LOG 2024-08-14T21:27:44.794Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-14T21:27:44.784Z
      build_journal

LOG 2024-08-14T21:27:44.767Z
      [audio]
      registering mixer start handler

LOG 2024-08-14T21:27:44.767Z
      [audio]
      binding mixer to message bus

LOG 2024-08-14T21:27:44.767Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-14T21:27:44.766Z
      monster_search_filters
      {}

LOG 2024-08-14T21:27:44.766Z
      init_scenes_panel

LOG 2024-08-14T21:27:44.762Z
      TOKEN IS CACHED

LOG 2024-08-14T21:27:44.757Z
      migrate_token_customizations starting to migrate mytokenfolders customizations

LOG 2024-08-14T21:27:44.757Z
      migrate_token_customizations finished migrating mytokenfolders customizations

LOG 2024-08-14T21:27:44.757Z
      migrate_token_customizations starting to migrate mytokens customizations

LOG 2024-08-14T21:27:44.757Z
      migrate_token_customizations finished migrating mytokens customizations

LOG 2024-08-14T21:27:44.757Z
      migrate_token_customizations has already completed

LOG 2024-08-14T21:27:44.755Z
      init_sidebar_tabs

LOG 2024-08-14T21:27:44.755Z
      init_tokens_panel

LOG 2024-08-14T21:27:44.607Z
      init_ui

LOG 2024-08-14T21:27:44.603Z
      DDBApi.fetchAllEncounters attempting to fetch 
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
