### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by sigkate** [cyruzzo/AboveVTT#2393]
**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/90c05d8f-8383-4370-8c99-c9c58eb5d145?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Chrome","version":"128","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-08-15T09:28:00.461Z
      TOKEN IS CACHED

LOG 2024-08-15T09:28:00.455Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-15T09:28:00.452Z
      build_journal

LOG 2024-08-15T09:28:00.440Z
      [audio]
      registering mixer start handler

LOG 2024-08-15T09:28:00.440Z
      [audio]
      binding mixer to message bus

LOG 2024-08-15T09:28:00.440Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-15T09:28:00.439Z
      monster_search_filters
      {}

LOG 2024-08-15T09:28:00.439Z
      init_scenes_panel

LOG 2024-08-15T09:28:00.438Z
      TOKEN IS CACHED

LOG 2024-08-15T09:28:00.433Z
      init_sidebar_tabs

LOG 2024-08-15T09:28:00.433Z
      init_tokens_panel

LOG 2024-08-15T09:28:00.433Z
      migrate_token_customizations starting to migrate mytokenfolders customizations

LOG 2024-08-15T09:28:00.433Z
      migrate_token_customizations finished migrating mytokenfolders customizations

LOG 2024-08-15T09:28:00.433Z
      migrate_token_customizations starting to migrate mytokens customizations

LOG 2024-08-15T09:28:00.433Z
      migrate_token_customizations finished migrating mytokens customizations

LOG 2024-08-15T09:28:00.433Z
      migrate_token_customizations has already completed

LOG 2024-08-15T09:28:00.401Z
      DDBApi.fetchAllEncounters successfully fetched page 7

LOG 2024-08-15T09:28:00.401Z
      
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
