### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by mcranej** [cyruzzo/AboveVTT#2394]
**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/8ceabaa8-efa1-4149-b8c2-9a460b85c744?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Chrome","version":"127","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-08-15T13:15:38.663Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T13:15:38.663Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T13:15:38.663Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T13:15:38.663Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T13:15:38.663Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T13:15:38.663Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T13:15:38.663Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T13:15:38.663Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T13:15:38.663Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T13:15:38.663Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T13:15:38.663Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T13:15:38.663Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T13:15:38.662Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T13:15:38.662Z
      parse_img is converting
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
