### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by alfamog** [cyruzzo/AboveVTT#2396]
**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/89fa00f8-711f-4212-bc86-5b64f0a0b760?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Chrome","version":"127","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-08-15T15:11:46.510Z
      TOKEN IS CACHED

LOG 2024-08-15T15:11:46.503Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-15T15:11:46.494Z
      build_journal

LOG 2024-08-15T15:11:46.478Z
      [audio]
      registering mixer start handler

LOG 2024-08-15T15:11:46.478Z
      [audio]
      binding mixer to message bus

LOG 2024-08-15T15:11:46.478Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-15T15:11:46.477Z
      monster_search_filters
      {}

LOG 2024-08-15T15:11:46.477Z
      init_scenes_panel

LOG 2024-08-15T15:11:46.475Z
      TOKEN IS CACHED

LOG 2024-08-15T15:11:46.472Z
      migrate_token_customizations finished migrating mytokenfolders customizations

LOG 2024-08-15T15:11:46.472Z
      migrate_token_customizations starting to migrate mytokens customizations

LOG 2024-08-15T15:11:46.472Z
      migrate_token_customizations finished migrating mytokens customizations

LOG 2024-08-15T15:11:46.472Z
      migrate_token_customizations has already completed

LOG 2024-08-15T15:11:46.471Z
      migrate_token_customizations starting to migrate mytokenfolders customizations

LOG 2024-08-15T15:11:46.470Z
      init_sidebar_tabs

LOG 2024-08-15T15:11:46.470Z
      init_tokens_panel

LOG 2024-08-15T15:11:46.412Z
      init_ui

LOG 2024-08-15T15:11:46.411Z
      DDBApi.fetchAllEncounters successfully fetched
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
