### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by RichardCariven** [cyruzzo/AboveVTT#2397]
**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/d7ca4aa7-10ff-4143-ab4e-a230062b9c6f?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Chrome","version":"127","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-08-15T18:04:11.776Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T18:04:11.662Z
      TOKEN IS CACHED

LOG 2024-08-15T18:04:11.648Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-15T18:04:11.636Z
      build_journal

LOG 2024-08-15T18:04:11.621Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-15T18:04:11.620Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T18:04:11.620Z
      [audio]
      registering mixer start handler

LOG 2024-08-15T18:04:11.620Z
      [audio]
      binding mixer to message bus

LOG 2024-08-15T18:04:11.619Z
      init_scenes_panel

LOG 2024-08-15T18:04:11.618Z
      monster_search_filters
      {}

LOG 2024-08-15T18:04:11.614Z
      TOKEN IS CACHED

LOG 2024-08-15T18:04:11.604Z
      migrate_token_customizations finished migrating mytokenfolders customizations

LOG 2024-08-15T18:04:11.604Z
      migrate_token_customizations starting to migrate mytokens customizations

LOG 2024-08-15T18:04:11.604Z
      migrate_token_customizations finished migrating mytokens customizations

LOG 2024-08-15T18:04:11.604Z
      migrate_token_customizations has already completed

LOG 2024-08-15T18:04:11.603Z
      migrate_token_customizations starting to migrate mytokenfolders customizations

LOG 2024-08-15T18:04:11.602Z
  
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
