### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by 3lBurrit0** [cyruzzo/AboveVTT#2399]
**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/87e338c0-8c6d-4e3c-8d22-5bce1b3c5652?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Chrome","version":"127","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-08-15T19:33:51.374Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T19:33:51.374Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T19:33:51.374Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T19:33:51.374Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T19:33:51.374Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T19:33:51.374Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T19:33:51.374Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T19:33:51.374Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T19:33:51.373Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-15T19:33:51.249Z
      TOKEN IS CACHED

LOG 2024-08-15T19:33:51.234Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-15T19:33:51.221Z
      build_journal

LOG 2024-08-15T19:33:51.204Z
      [audio]
      registering mixer start handler

LOG 2024-08-15T19:33:51.204Z
      [audio]
      binding mixer to message bus

LOG 2024-08-15T19:33:51.204Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-15T19:33:51.203Z
  
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
