### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by nmelcer** [cyruzzo/AboveVTT#2401]
**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/dd3dca25-967f-47b2-8fde-c2df8aa6ce0e?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Opera"}}
```
**Other Logs:**
```

LOG 2024-08-15T23:07:36.341Z
      TOKEN IS CACHED

LOG 2024-08-15T23:07:36.316Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-15T23:07:36.307Z
      build_journal

LOG 2024-08-15T23:07:36.287Z
      [audio]
      registering mixer start handler

LOG 2024-08-15T23:07:36.287Z
      [audio]
      binding mixer to message bus

LOG 2024-08-15T23:07:36.287Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-15T23:07:36.286Z
      monster_search_filters
      {}

LOG 2024-08-15T23:07:36.286Z
      init_scenes_panel

LOG 2024-08-15T23:07:36.283Z
      TOKEN IS CACHED

LOG 2024-08-15T23:07:36.277Z
      migrate_token_customizations has already completed

LOG 2024-08-15T23:07:36.276Z
      migrate_token_customizations starting to migrate mytokenfolders customizations

LOG 2024-08-15T23:07:36.276Z
      migrate_token_customizations finished migrating mytokenfolders customizations

LOG 2024-08-15T23:07:36.276Z
      migrate_token_customizations starting to migrate mytokens customizations

LOG 2024-08-15T23:07:36.276Z
      migrate_token_customizations finished migrating mytokens customizations

LOG 2024-08-15T23:07:36.275Z
      init_tokens_panel

LOG 2024-08-15T23:07:36.274Z
      init_sidebar_tabs

LOG 2024-08-15T23:07:36.140Z
      init_ui

LOG 2024-08-15T23:07:36.138Z
      DDBApi.fetchAllEncounters attempting to fetch pages 2 through 1

LOG 2024-08-15T23:07:36.138Z
      startup_step Setting up UI

LOG 202
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
