### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by bluejack** [cyruzzo/AboveVTT#2402]
Went to start my game as DM tonight and got this. 

**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/501f0426-85ed-485a-a792-b399c9ac4bf5?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Chrome","version":"127","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-08-16T00:59:51.826Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T00:59:51.826Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T00:59:51.826Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T00:59:51.826Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T00:59:51.826Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T00:59:51.826Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T00:59:51.826Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T00:59:51.743Z
      TOKEN IS CACHED

LOG 2024-08-16T00:59:51.736Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-16T00:59:51.714Z
      build_journal

LOG 2024-08-16T00:59:51.691Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T00:59:51.691Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T00:59:51.691Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T00:59:51.691Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T00:59:51.691Z
      parse_img is converting
      unde
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
