### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by DeminStriphon** [cyruzzo/AboveVTT#2403]
**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/830608a4-12ca-4dcc-a7de-bd5fa88b48ee?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Opera"}}
```
**Other Logs:**
```

LOG 2024-08-16T01:33:44.097Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T01:33:44.097Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T01:33:44.097Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T01:33:44.055Z
      TOKEN IS CACHED

LOG 2024-08-16T01:33:44.042Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-16T01:33:44.023Z
      build_journal

LOG 2024-08-16T01:33:44.015Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T01:33:44.015Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T01:33:44.015Z
      parse_img is converting
      undefined
      to an empty string

LOG 2024-08-16T01:33:44.015Z
      [audio]
      registering mixer start handler

LOG 2024-08-16T01:33:44.015Z
      [audio]
      binding mixer to message bus

LOG 2024-08-16T01:33:44.015Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-16T01:33:44.014Z
      monster_search_filters
      {}

LOG 2024-08-16T01:33:44.014Z
      init_scenes_panel

LOG 2024-08-16T01:33:44.013Z
      TOKEN IS CACHED

LOG 2024-08-16T01:33:44.008Z
      migrate_token_customizations starting to migrate mytokenfolders customizations

LOG 2024-08-16T01:33:44.008Z
      migrate_token_customizations finished migrating mytokenfolders customizations

LOG 2024-08-16T01:33
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
