### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by cseich11** [cyruzzo/AboveVTT#2405]
**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/ed2f4e8f-b623-4233-a94d-ebfd47aae48b?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Chrome","version":"127","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-08-16T02:58:18.849Z
      TOKEN IS CACHED

LOG 2024-08-16T02:58:18.836Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-16T02:58:18.828Z
      build_journal

LOG 2024-08-16T02:58:18.816Z
      [audio]
      registering mixer start handler

LOG 2024-08-16T02:58:18.816Z
      [audio]
      binding mixer to message bus

LOG 2024-08-16T02:58:18.816Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-16T02:58:18.815Z
      monster_search_filters
      {}

LOG 2024-08-16T02:58:18.815Z
      init_scenes_panel

LOG 2024-08-16T02:58:18.812Z
      TOKEN IS CACHED

LOG 2024-08-16T02:58:18.808Z
      migrate_token_customizations starting to migrate mytokenfolders customizations

LOG 2024-08-16T02:58:18.808Z
      migrate_token_customizations finished migrating mytokenfolders customizations

LOG 2024-08-16T02:58:18.808Z
      migrate_token_customizations starting to migrate mytokens customizations

LOG 2024-08-16T02:58:18.808Z
      migrate_token_customizations finished migrating mytokens customizations

LOG 2024-08-16T02:58:18.808Z
      migrate_token_customizations has already completed

LOG 2024-08-16T02:58:18.807Z
      init_tokens_panel

LOG 2024-08-16T02:58:18.806Z
      init_sidebar_tabs

LOG 2024-08-16T02:58:18.750Z
      init_ui

LOG 2024-08-16T02:58:18.749Z
      DDBApi.fetchAllEncounters attempting to fetch 
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.

**Comment by cseich11** [comment]
Confirmed fixed
