### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by IdArcanaRes** [cyruzzo/AboveVTT#2406]
**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/3a045b51-38c8-441b-81e6-25e0846280d8?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Chrome","version":"127","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-08-16T03:22:33.605Z
      TOKEN IS CACHED

LOG 2024-08-16T03:22:33.578Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-16T03:22:33.555Z
      build_journal

LOG 2024-08-16T03:22:33.528Z
      [audio]
      binding mixer to message bus

LOG 2024-08-16T03:22:33.528Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-16T03:22:33.527Z
      [audio]
      registering mixer start handler

LOG 2024-08-16T03:22:33.525Z
      init_scenes_panel

LOG 2024-08-16T03:22:33.524Z
      monster_search_filters
      {}

LOG 2024-08-16T03:22:33.519Z
      TOKEN IS CACHED

LOG 2024-08-16T03:22:33.507Z
      migrate_token_customizations starting to migrate mytokenfolders customizations

LOG 2024-08-16T03:22:33.507Z
      migrate_token_customizations finished migrating mytokenfolders customizations

LOG 2024-08-16T03:22:33.507Z
      migrate_token_customizations starting to migrate mytokens customizations

LOG 2024-08-16T03:22:33.507Z
      migrate_token_customizations finished migrating mytokens customizations

LOG 2024-08-16T03:22:33.507Z
      migrate_token_customizations has already completed

LOG 2024-08-16T03:22:33.504Z
      init_tokens_panel

LOG 2024-08-16T03:22:33.503Z
      init_sidebar_tabs

LOG 2024-08-16T03:22:33.323Z
      init_ui

LOG 2024-08-16T03:22:33.321Z
      DDBApi.fetchAllEncounters attempting to fetch 
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
