### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by renatovalezin** [cyruzzo/AboveVTT#2407]
Everytime I load the VTT it give this message:

**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/d25dfe58-683a-4d64-8332-770d93cc2727?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Chrome","version":"127","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-08-16T14:13:02.292Z
      TOKEN IS CACHED

LOG 2024-08-16T14:13:02.284Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-16T14:13:02.277Z
      build_journal

LOG 2024-08-16T14:13:02.268Z
      [audio]
      registering mixer start handler

LOG 2024-08-16T14:13:02.268Z
      [audio]
      binding mixer to message bus

LOG 2024-08-16T14:13:02.268Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-16T14:13:02.267Z
      monster_search_filters
      {}

LOG 2024-08-16T14:13:02.267Z
      init_scenes_panel

LOG 2024-08-16T14:13:02.265Z
      TOKEN IS CACHED

LOG 2024-08-16T14:13:02.260Z
      migrate_token_customizations has already completed

LOG 2024-08-16T14:13:02.259Z
      migrate_token_customizations starting to migrate mytokenfolders customizations

LOG 2024-08-16T14:13:02.259Z
      migrate_token_customizations finished migrating mytokenfolders customizations

LOG 2024-08-16T14:13:02.259Z
      migrate_token_customizations starting to migrate mytokens customizations

LOG 2024-08-16T14:13:02.259Z
      migrate_token_customizations finished migrating mytokens customizations

LOG 2024-08-16T14:13:02.258Z
      init_tokens_panel

LOG 2024-08-16T14:13:02.257Z
      init_sidebar_tabs

LOG 2024-08-16T14:13:02.188Z
      init_ui

LOG 2024-08-16T14:13:02.187Z
      DDBApi.fetchAllEncounters successfully fetched
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
