### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by hbarbosa02** [cyruzzo/AboveVTT#2408]
**Error:**
```
Cannot read properties of undefined (reading 'replace')
Failed to start AboveVTT on https://www.dndbeyond.com/encounters/207cb252-4dd5-4b47-b7be-bbad1cce6a5e?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'replace')
    at init_ui (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Main.js:2747:19)
    at start_above_vtt_for_dm (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:409:3)
```
**Environment:**
```
{"avttVersion":"1.22","browser":{"name":"Chrome","version":"127","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-08-16T16:35:49.761Z
      TOKEN IS CACHED

LOG 2024-08-16T16:35:49.742Z
      redraw_settings_panel_token_examples
      undefined

LOG 2024-08-16T16:35:49.732Z
      build_journal

LOG 2024-08-16T16:35:49.729Z
      [audio]
      pushing mixer state to players
      {"paused":false,"channels":{},"playlists":{"4bdc0d5e-8746-430b-8244-57afc72195da":{"channels":{},"volume":"1","paused":false,"name":"Default"}},"selected":"4bdc0d5e-8746-430b-8244-57afc72195da"}

LOG 2024-08-16T16:35:49.709Z
      [audio]
      registering mixer start handler

LOG 2024-08-16T16:35:49.709Z
      [audio]
      binding mixer to message bus

LOG 2024-08-16T16:35:49.709Z
      [audio]
      initializing audio ui for DM

LOG 2024-08-16T16:35:49.707Z
      monster_search_filters
      {}

LOG 2024-08-16T16:35:49.707Z
      init_scenes_panel

LOG 2024-08-16T16:35:49.703Z
      TOKEN IS CACHED

LOG 2024-08-16T16:35:49.696Z
      migrate_token_customizations starting to migrate mytokenfolders customizations

LOG 2024-08-16T16:35:49.696Z
      migrate_token_customizations finished migrating mytokenfolders customizations

LOG 2024-08-16T16:35:49.696Z
      migrate_token_customizations starting to migrate mytokens customizations

LOG 2024-08-16T16:35:49.696Z
      migrate_token_customizations finished migrating mytokens customizations

LOG 2024-08-16T16:35:49.696Z
      mig
```

**Comment by Azmoria** [comment]
DDB made some changes that caused this error on DM side. Should be fixed in the version pushed out today.
