### ISSUE TITLE
Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

### ISSUE THREAD

**Issue by tallcupofcoffee** [cyruzzo/AboveVTT#2520]
**Error:**
```
Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at redraw_drawings (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Fog.js:1420:6)
    at reset_canvas (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Fog.js:1112:2)
    at MessageBroker.handleScene (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/MessageBroker.js:1777:11)
```
**Environment:**
```
{"avttVersion":"1.24","browser":{"name":"Chrome","version":"129","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-09-27T19:00:59.053Z
      AboveApi.getScene(7510c72f-efdb-4749-9279-4019424f02e6)
      {"objectId":"scenes#7510c72f-efdb-4749-9279-4019424f02e6#scenedata","campaignId":"[REDACTED]","sceneId":"7510c72f-efdb-4749-9279-4019424f02e6","data":{"itemType":"scene","thumb":"https://media.dndbeyond.com/compendium-images/pbtso/3WCYZRRvYTovFYbD/03-008.Map303-Wyvern-Tor.png","reveals":[[0,0,0,0,2,0,1]],"gridStrokeNumberInput":"0.5","scale":100,"vpps":"52.666666666666664","darkness_filter_number":"100","title":"Map 3.3: Wyvern Tor","fog_of_war":"1","uuid":"dnd/pbtso/the-spiders-web/Map303WyvernTor","player_map":"https://media.dndbeyond.com/compendium-images/pbtso/3WCYZRRvYTovFYbD/03-008.Map303-Wyvern-Tor.png","upsq":"ft","scaleX":1,"folderPath":"/Phandelver and Below/The Spider's Web","scaleY":1,"playlist":"0","gridType":"1","drawings":[["line","wall","rgba(0, 255, 0, 1)",27,1015,84,1002,6,1],["line","wall","rgba(0, 255, 0, 1)",84,1002,139,986,6,1],["line","wall","rgba(0, 255, 0, 1)",139,986,175,988,6,1],["line","wall","rgba(0, 255, 0, 1)",175,988,193,984,6,1],["line","wall","rgba(0, 255, 0, 1)",193,984,218,945,6,1],["line","wall","rgba(0, 255, 0, 1)",218,945,248,918,6,1],["line","wall","rgba(0, 255, 0, 1)",248,918,320,900,
```

**Comment by Azmoria** [comment]
duplicate of #2515  - closing to clean up a bit
