### ISSUE TITLE
Cannot read properties of undefined (reading 'json')

### ISSUE THREAD

**Issue by DankHill2020** [cyruzzo/AboveVTT#2663]
**Error:**
```
Cannot read properties of undefined (reading 'json')
Failed to start AboveVTT on https://www.dndbeyond.com/characters/29076498?abovevtt=true
TypeError: Cannot read properties of undefined (reading 'json')
    at DDBApi.fetchJsonWithToken (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:59:26)
    at async DDBApi.fetchCampaignInfo (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:184:22)
    at async start_above_vtt_common (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:358:26)
    at async start_above_vtt_for_players (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:456:3)
```
**Environment:**
```
{"avttVersion":"1.27","browser":{"name":"Chrome","version":"130","mozilla":false,"chrome":true,"msie":false,"opera":false,"safari":false}}
```
**Other Logs:**
```

LOG 2024-11-19T02:42:55.194Z
      showErrorMessage
      Error: DDB API Error: Unknown Error 404 
    at lookForErrors (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:43:17)
    at async DDBApi.fetchJsonWithToken (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:58:21)
    at async DDBApi.fetchCampaignInfo (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/DDBApi.js:184:22)
    at async start_above_vtt_common (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:358:26)
    at async start_above_vtt_for_players (chrome-extension://ipcjcbhpofedihcloggaichibomadlei/Startup.js:456:3)

ERROR 2024-11-19T02:42:55.193Z
      DDB API Error: Unknown Error 404 

ERROR 2024-11-19T02:42:55.192Z
      DDBApi.lookForErrors Failed to parse json
      {}
      {}

LOG 2024-11-19T02:42:54.153Z
      DDBApi.fetchCampaignInfo

LOG 2024-11-19T02:42:54.152Z
      startup_step Starting AboveVTT for character

LOG 2024-11-19T02:42:54.152Z
      start_above_vtt_common

LOG 2024-11-19T02:42:54.104Z
      harvest_campaign_secret found it by loading the campaign page in an iframe

ERROR 2024-11-19T02:42:53.197Z
      Failed to p
```

**Comment by Azmoria** [comment]
I've seen this reported before - it's failing to get campaign data from DDB. 

Few things to try

1) Try joining from the campaign page - Make sure you're on the latest version - there was an issue after a ddb update not too long ago with getting campaign id. It may be missing the campaign id for some reason if something is changed again.

3)  Try clearing `cached images and files`.

 As long as you **don't** select `cookies/other site data` it shouldn't clear any abovevtt data but you can take exports to be safe.

You may have to restart the browser after clearing this.

![image](https://github.com/user-attachments/assets/66d57c1d-9f28-4c59-8a13-775118495342)

**Comment by Azmoria** [comment]
From recent reports this is generally DDB's 'are you human' check preventing requests - there's been an uptick in reports of this across DDBs forums and discord (not just abovevtt related).

For some reason you may have to check an incognito window to see and clear the are you a bot message. Closing just due to duplicate for now - still on our radar to see if it's something we can resolve or a DDB issue.
